#!/usr/bin/env python3
"""Phase 3b 매니페스트 생성기.

docs/faith-book-catalog-phase3.md에서 도서 목록을 파싱하여
p3a에 포함되지 않은 나머지 도서의 매니페스트를 생성합니다.
"""

import json, re
from pathlib import Path

P3A = Path("pipeline/scripts/books_manifest_p3a.json")
CATALOG = Path("docs/faith-book-catalog-phase3.md")
OUT = Path("pipeline/scripts/books_manifest_p3b.json")

# ─── CCEL URL 매핑 ───
# 알려진 CCEL 경로 매핑
CCEL_PATHS = {
    # ANF volumes
    "anf-vol1-justin-remains": "anf01", "anf-vol1-tatian": "anf01",
    "anf-vol1-athenagoras": "anf01", "anf-vol2-clement-misc": "anf02",
    "anf-vol3-tertullian-v2": "anf03", "anf-vol3-tertullian-v3": "anf03",
    "anf-vol4-tertullian-v4": "anf04", "anf-vol4-minucius-felix": "anf04",
    "anf-vol4-commodian": "anf04", "anf-vol5-hippolytus": "anf05",
    "anf-vol5-novatian": "anf05", "anf-vol6-gregory-thaumaturgus": "anf06",
    "anf-vol6-dionysius-alex": "anf06", "anf-vol6-methodius": "anf06",
    "anf-vol6-arnobius": "anf06", "anf-vol7-lactantius": "anf07",
    "anf-vol7-venantius": "anf07", "anf-vol7-apostolic-constitutions": "anf07",
    "anf-vol8-pseudo-clementine": "anf08", "anf-vol9-syriac-documents": "anf09",
    # NPNF1 volumes
    "npnf1-vol1-augustine-confessions-full": "npnf101",
    "npnf1-vol1-augustine-letters-sel": "npnf101",
    "npnf1-vol2-city-of-god-v2": "npnf102",
    "npnf1-vol4-augustine-anti-donatist": "npnf104",
    "npnf1-vol5-augustine-anti-pelagian": "npnf105",
    "npnf1-vol6-augustine-sermon-mount": "npnf106",
    "npnf1-vol7-augustine-homilies-john": "npnf107",
    "npnf1-vol8-augustine-psalms-sel": "npnf108",
    "npnf1-vol10-chrysostom-matthew-v2": "npnf110",
    "npnf1-vol11-chrysostom-acts-rom": "npnf111",
    "npnf1-vol12-chrysostom-corinthians": "npnf112",
    "npnf1-vol13-chrysostom-galatians": "npnf113",
    "npnf1-vol14-chrysostom-hebrews": "npnf114",
    # NPNF2 volumes
    "npnf2-vol1-eusebius-extra": "npnf201",
    "npnf2-vol2-socrates-sozomen-extra": "npnf202",
    "npnf2-vol3-theodoret-extra": "npnf203",
    "npnf2-vol4-athanasius-extra": "npnf204",
    "npnf2-vol5-gregory-nyssa-extra2": "npnf205",
    "npnf2-vol6-jerome-extra": "npnf206",
    "npnf2-vol7-cyril-gregory-extra": "npnf207",
    "npnf2-vol8-basil-extra2": "npnf208",
    "npnf2-vol9-hilary-poitiers": "npnf209",
    "npnf2-vol9-john-damascene-extra": "npnf209",
    "npnf2-vol10-ambrose-extra": "npnf210",
    "npnf2-vol11-sulpicius-cassian-extra": "npnf211",
    "npnf2-vol12-leo-gregory-great-extra": "npnf212",
    "npnf2-vol13-ephraim-aphrahat": "npnf213",
    "npnf2-vol14-seven-ecumenical": "npnf214",
    "npnf2-vol14-excursus": "npnf214",
    # Chrysostom homilies
    "chrysostom-genesis-homilies-sel": "npnf109",
    "chrysostom-john-homilies-sel": "npnf114",
    "chrysostom-ephesians-homilies": "npnf113",
    "chrysostom-philippians-homilies": "npnf113",
    "chrysostom-timothy-titus": "npnf113",
    # Augustine
    "augustine-de-trinitate-full": "npnf103",
    "augustine-retractions": "npnf101",
    "augustine-soliloquies": "npnf107",
    "augustine-free-will": "npnf105",
    "augustine-catechizing-uninstructed": "npnf103",
    "augustine-continence": "npnf103",
    # CCEL standalone works
    "eusebius-church-history": "npnf201",
    "eusebius-life-constantine": "npnf201",
    "eusebius-martyrs-palestine": "npnf201",
    "socrates-church-history": "npnf202",
    "sozomen-church-history": "npnf202",
    "theodoret-church-history": "npnf203",
    "theodoret-religious-history": "npnf203",
    "sulpicius-life-martin": "npnf211",
    "cyril-jerusalem-catechetical": "npnf207",
    "ephrem-syrian-hymns-sel": "npnf213",
    "dionysius-areopagite-full": "npnf201",  # approximate
    # Spurgeon
    "spurgeon-treasury-david-v7": "spurgeon/treasury7",
    "spurgeon-soul-winner": "spurgeon/soulwinner",
    "spurgeon-commenting-commentaries": "spurgeon/comment",
    "spurgeon-according-to-promise": "spurgeon/according",
    "spurgeon-come-ye-children": "spurgeon/children",
    # Bounds
    "bounds-preacher-prayer": "bounds/preacher",
    "bounds-purpose-prayer": "bounds/purpose",
    "bounds-weapon-prayer": "bounds/weapon",
    "bounds-necessity-prayer": "bounds/necessity",
    "bounds-possibilities-prayer": "bounds/possibilities",
    "bounds-reality-prayer": "bounds/reality",
    "bounds-essentials-prayer": "bounds/essentials",
    # Murray
    "murray-master-secret": "murray/indwelling",
    "murray-inner-chamber": "murray/innerchamber",
    "murray-like-christ": "murray/like_christ",
    "murray-full-blessing": "murray/full_blessing",
    "murray-new-life": "murray/new_life",
    "murray-state-of-church": "murray/state_church",
    "murray-ministry-intercession": "murray/intercession",
    "murray-raising-dead": "murray/raising",
    # Owen
    "owen-death-of-death": "owen/deathofdeath",
    "owen-justification": "owen/just",
    "owen-person-of-christ": "owen/person",
    "owen-hebrews-sel-v1": "owen/hebrews1",
    "owen-hebrews-sel-v2": "owen/hebrews2",
    "owen-biblical-theology-sel": "owen/biblical",
    # Calvin commentaries
    "calvin-commentary-genesis": "calvin/calcom01",
    "calvin-commentary-exodus-deut": "calvin/calcom03",
    "calvin-commentary-joshua": "calvin/calcom07",
    "calvin-commentary-isaiah-sel": "calvin/calcom13",
    "calvin-commentary-jeremiah-sel": "calvin/calcom17",
    "calvin-commentary-minor-prophets": "calvin/calcom26",
    "calvin-commentary-john": "calvin/calcom34",
    "calvin-commentary-acts-sel": "calvin/calcom36",
    "calvin-commentary-corinthians": "calvin/calcom39",
    "calvin-commentary-galatians-eph": "calvin/calcom41",
    "calvin-commentary-philippians-col": "calvin/calcom42",
    "calvin-commentary-timothy-titus": "calvin/calcom43",
    "calvin-commentary-hebrews": "calvin/calcom44",
    # Palladius
    "palladius-lausiac-history": "npnf211",
    # Kuyper
    "kuyper-lectures-calvinism": "kuyper/lectures",
    # Various CCEL
    "drummond-natural-law": "drummond/naturallaw",
    "drummond-greatest-thing": "drummond/greatest",
    "spurgeon-eccentric-preachers": "spurgeon/eccentric",
    "mccheyne-sermons-remains": "mccheyne/remains",
    # Other Puritans/Reformed
    "charnock-new-birth": "charnock/newbirth",
    "charnock-sinfulness-sin": "charnock/sinfulness",
    "flavel-england-duty-sel": "flavel/england",
    "flavel-sacramental-meditations": "flavel/sacramental",
    "boston-crook-in-lot": "boston/crook",
    "boston-covenant-of-grace": "boston/covenant",
    "manton-sermons-psalm119-sel": "manton/psalm119",
    "shepard-parable-ten-virgins": "shepard/virgins",
    "shepard-sound-believer": "shepard/sound",
    "shepard-sincere-convert": "shepard/sincere",
    "rutherford-trial-triumph": "rutherford/trial",
    "rutherford-letters-v1": "rutherford/letters",
    "rutherford-letters-v2": "rutherford/letters",
    "ursinus-commentary-catechism": "ursinus/catechism",
    "goodwin-patience-saints": "goodwin/patience",
    "goodwin-glory-gospel": "goodwin/glory",
    "goodwin-return-of-prayers": "goodwin/return",
    "goodwin-works-sel": "goodwin/works",
    "brooks-unsearchable-riches": "brooks/riches",
    "brooks-apples-gold": "brooks/gold",
    "watson-doctrine-of-repentance": "watson/repentance",
    "watson-godly-mans-picture": "watson/godlyman",
    "sibbes-fountain-sealed": "sibbes/fountain",
    "sibbes-glorious-freedom": "sibbes/freedom",
    "burroughs-gospel-reconciliation": "burroughs/reconciliation",
    "perkins-art-prophesying": "perkins/art",
    "guyon-spiritual-progress": "guyon/spiritual",
    "baxter-dying-thoughts": "baxter/dying",
    "baxter-saints-rest-full": "baxter/saints_rest",
    "scots-confession": "creeds/scots",
    "savoy-declaration": "creeds/savoy",
    "london-baptist-confession": "creeds/london",
    "thirty-nine-articles": "creeds/thirtynine",
    "irish-articles": "creeds/irish",
    "formula-of-concord": "creeds/concord",
    "ames-marrow-theology": "ames/marrow",
    "julian-norwich-revelations-full": "julian/revelations",
}

# ─── Gutenberg ID 매핑 ───
GUTENBERG_IDS = {
    "macdonald-phantastes": 325,
    "macdonald-lilith": 1640,
    "macdonald-princess-goblin": 708,
    "macdonald-princess-curdie": 709,
    "macdonald-at-back-north-wind": 225,
    "macdonald-robert-falconer": 6755,
    "macdonald-sir-gibbie": 5491,
    "sheldon-in-his-steps": 4851,
    "lew-wallace-ben-hur": 4126,
    "sienkiewicz-quo-vadis": 4952,
    "kingsley-hypatia": 7066,
    "kingsley-westward-ho-sel": 5096,
    "yonge-heir-redclyffe": 3424,
    "yonge-daisy-chain": 3610,
    "ingraham-prince-house-david": 13508,
    "phelps-gates-ajar": 1550,
    "mulock-john-halifax": 2351,
    "newman-callista": 1254,
    "bunyan-badman": 4631,
    "wilberforce-practical-christianity": 25709,
    "way-of-pilgrim": 43093,
    "bede-ecclesiastical-history": 38326,
    "motley-dutch-republic-sel": 4835,
    "daubigne-reformation-v1": 46683,
    "daubigne-reformation-v2": 46769,
    "daubigne-reformation-v3": 46929,
    "daubigne-reformation-v4": 46989,
    "daubigne-reformation-v5": 46990,
    "spurgeon-farm-sermons": 42518,
    "spurgeon-gleanings-sermons": 42657,
    "spurgeon-feathers-arrows": 42515,
    "spurgeon-according-to-promise": 42516,
    "spurgeon-come-ye-children": 42519,
    "spurgeon-christs-words-cross": 42520,
    "spurgeon-twelve-sermons-holy-spirit": 42653,
    "spurgeon-twelve-striking-sermons": 42654,
    "stalker-life-jesus": 8384,
    "stalker-life-paul": 8385,
    "moody-way-to-god-expanded": 42493,
    "moody-men-of-bible": 42494,
    "moody-sowing-reaping": 42495,
    "moody-heaven": 42496,
    "moody-to-the-work": 42497,
    "moody-twelve-select-sermons": 42498,
    "moody-short-talks": 42499,
    "gordon-quiet-talks-jesus": 32735,
    "gordon-quiet-talks-service": 32736,
    "gordon-quiet-talks-home-ideals": 32737,
    "gordon-quiet-talks-personal-problems": 32738,
    "gordon-quiet-talks-tempter": 32739,
    "gordon-quiet-talks-simple-essentials": 32740,
    "smith-unselfishness-of-god": 19597,
    "chesterton-napoleon-notting-hill": 20058,
    "chesterton-flying-inn": 1687,
    "chesterton-man-who-was-thursday": 1695,
    "chesterton-club-queer-trades": 1696,
    "chesterton-varied-types": 12245,
    "chesterton-autobiography": 12632,
    "pascal-minor-works": 6946,
    "pascal-mystery-jesus": 6946,
    "newman-apologia": 35897,
    "newman-idea-university-sel": 24526,
    "newman-grammar-assent": 39076,
    "milton-samson-agonistes": 1570,
    "milton-comus": 1565,
    "milton-areopagitica": 608,
    "hopkins-poems-sel": 22878,
    "whittier-religious-poems": 9583,
    "torrey-how-bring-men-christ": 42501,
    "gale-korean-sketches": 45137,
    "mckenzie-korea-tragedy": 57769,
    "sheldon-crucifixion-philip-strong": 4852,
    "josephus-wars-sel": 2850,
    "luther-commentary-galatians-full": 1549,
    "smith-every-day-religion": 19598,
    "talmage-around-tea-table": 39077,
    "thompson-hound-heaven": 11376,
    "wiseman-fabiola": 23377,
    "corelli-barabbas": 7063,
    "shorthouse-john-inglesant": 15766,
}

# ─── Archive.org ID 매핑 ───
# 형식: slug → archive identifier
ARCHIVE_IDS = {
    "adam-bremen-history": "historyofarchbis00adam",
    "william-malmesbury-gesta": "gestaregunanglo01malmgoog",
    "wylie-history-protestantism-v1": "historyofprotest01wyli",
    "wylie-history-protestantism-v2": "historyofprotest02wyli",
    "wylie-history-protestantism-v3": "historyofprotest03wyli",
    "latourette-missions-sel": "historyofexpansi01lato",
    "kurtz-church-history": "churchhistoryv1k00kurtgoog",
    "neander-church-history-sel": "generalhisto01nean",
    "milman-latin-christianity-sel": "historyoflatinch01milm",
    "fisher-history-reformation": "historyofreforma00fish",
    "harnack-expansion-sel": "missionandexpans01harn",
    "robertson-history-church-sel": "historyofchristi01robe",
    "stanley-eastern-church": "lecturesonhistor00stan",
    "waddington-church-history-sel": "historyofchurch00wadd",
    "broadus-history-preaching": "historyofpreachi00broa",
    "killen-ancient-church": "ancientchurch00kill",
    "sulpicius-sacred-history": "sacredhistory00sulp",
    "sayings-desert-fathers": "sayingsofdesertf00ward",
    "john-climacus-ladder": "ladderofdivineas00john",
    "evagrius-praktikos": "praktikoschapter00evag",
    "dorotheos-gaza-instructions": "dorotheusofgazad00doro",
    "isaac-syrian-homilies-sel": "asceticalhomilie00isaa",
    "pachomius-rules": "pachomiankoino01verf",
    "maximus-confessor-centuries": "centuriesonlove00maxi",
    "maximus-confessor-ambigua-sel": "ambiguatostthoma00maxi",
    "symeon-new-theologian-sel": "discoursesofnewt00syme",
    "gregory-palamas-triads-sel": "triadsindefe00greg",
    "cyril-alex-on-john-sel": "commentaryongos100cyri",
    "philokalia-sel-v1": "philokalia01palm",
    "philokalia-sel-v2": "philokalia02palm",
    "theophan-recluse-prayer": "artofprayer00theo",
    "theophan-recluse-path": "pathtosalvation00theo",
    "tikhon-zadonsk-sel": "journeytoheaven00tikh",
    "john-kronstadt-my-life": "mylifeinchrist00john",
    "ignatius-brianchaninov-sel": "arenaguidelines00igna",
    "nil-sorsky-tradition": "nilsorsky00malk",
    "optina-elders-sel": "optinaelders00rose",
    "russian-primary-chronicle-sel": "russianprimarych00cros",
    "seraphim-sarov-conversations": "conversationwith00moto",
    "rauschenbusch-christianity-social-crisis": "christianitysoci00raus",
    "rauschenbusch-theology-social-gospel": "theologyforsocia00raus",
    "gladden-applied-christianity": "appliedchristian00glad",
    "gladden-social-salvation": "socialsalvation00glad",
    "strong-josiah-our-country": "ourcountryitspos00stro",
    "mathews-social-teaching-jesus": "socialteachingof00math",
    "peabody-jesus-christ-social-question": "jesuschristandso00peab",
    "kuyper-work-holy-spirit-sel": "workofholyspiritinkuyperuoft",
    "maurice-kingdom-christ-sel": "kingdomofchrist01maur",
    "gore-lux-mundi-sel": "luxmundiaseries00gore",
    "ritschl-justification-sel": "justificationan00ritsgoog",
    "forsyth-work-of-christ": "workofchrist00fors",
    "forsyth-positive-preaching": "positivepreachin00fors",
    "ely-social-aspects-christianity": "socialaspectsofchristianityely",
    "headlam-christian-theology": "christiantheolog00head",
    "bridges-christian-ministry": "christianminist00brid",
    "spencer-pastors-sketches": "pastorssketches01spen",
    "spencer-pastors-sketches-v2": "pastorssketches02spen",
    "fairbairn-pastoral-epistles": "commentaryonpast00fair",
    "fairbairn-typology": "typologyofscript01fair",
    "alexander-james-thoughts-preaching": "thoughtsonpreach00alex",
    "kidder-homiletics": "treatiseonhomile00kidd",
    "shedd-homiletics": "homileticsandpas00shed",
    "murphy-pastoral-theology": "pastoraltheology00murp",
    "vinet-pastoral-theology": "pastoraltheology00vine",
    "mcneill-cure-of-souls-sel": "historyofcureof00mcne",
    "dabney-sacred-rhetoric": "sacredrhetoric00dabn",
    "phelps-men-and-books": "menandbooks00phel",
    "phelps-theory-of-preaching": "theoryofpreachin00phel",
    "watson-john-cure-of-souls": "cureofsouls00wats",
    "jowett-preacher-his-life": "preacherhislifea00jowe",
    "jefferson-minister-as-shepherd": "ministerasshephe00jeff",
    "oman-concerning-ministry": "concerningminist00oman",
    "forsyth-soul-of-prayer": "soulofprayer00fors",
    "edersheim-life-times-jesus-v1": "lifetimesofjesus01eder",
    "edersheim-life-times-jesus-v2": "lifetimesofjesus02eder",
    "edersheim-temple-services": "templeministryan00eder",
    "farrar-life-christ-v1": "lifeofchrist01farr",
    "farrar-life-christ-v2": "lifeofchrist02farr",
    "farrar-life-paul-v1": "lifeworkofstpaul01farr",
    "farrar-life-paul-v2": "lifeworkofstpaul02farr",
    "farrar-early-days-christianity": "earlydaysofchris00farr",
    "conybeare-howson-paul-sel": "lifeandepistleso01cony",
    "lightfoot-biblical-essays": "biblicalessays00ligh",
    "lightfoot-apostolic-fathers-intro": "apostolicfathers01ligh",
    "ramsay-paul-traveller": "stpaultravellera00rams",
    "ramsay-church-roman-empire": "churchinromanem00rams",
    "smith-old-testament-history": "oldtestamenthist00smit",
    "morgan-gospel-matthew": "gospelaccording00morg",
    "morgan-gospel-mark": "gospelaccording01morg",
    "morgan-gospel-luke": "gospelaccording02morg",
    "morgan-gospel-john": "gospelaccording03morg",
    "morgan-acts-of-apostles": "actsofapostles00morg",
    "morgan-westminster-pulpit-v1": "westminsterpulpi01morg",
    "morgan-westminster-pulpit-v2": "westminsterpulpi02morg",
    "morgan-ten-commandments": "tencommandments00morg",
    "parker-peoples-bible-sel-v2": "peoplesbibledisc02park",
    "parker-inner-life-of-christ-v1": "innerlifeofchris01park",
    "parker-inner-life-of-christ-v2": "innerlifeofchris02park",
    "parker-inner-life-of-christ-v3": "innerlifeofchris03park",
    "pierson-many-infallible-proofs": "manyinfalliblepr00pier",
    "pierson-new-acts-apostles": "newactsofapostles00pier",
    "simpson-gospel-john": "gospelaccording04simp",
    "simpson-christ-in-bible-sel": "christinthebible00simp",
    "simpson-larger-christian-life": "selflifeandchris00simp",
    "chadwick-gospel-mark": "gospelofstmark00chad",
    "dods-first-corinthians": "firstcorinthians00dods",
    "dale-ephesians": "lecturesonephesi00dale",
    "liddon-divinity-lord": "divinityourlord00lidd",
    "maclaren-colossians-philemon": "colossiansphi00macl",
    "moule-philippian-studies": "philippianstudi00moul",
    "moule-ephesian-studies": "ephesianstudies00moul",
    "moule-colossian-studies": "colossianstudies00moul",
    "whyte-appreciation-literature": "appreciationlit00whyt",
    "whyte-lord-teach-us-pray": "lordteachustopr00whyt",
    "jowett-high-calling": "highcalling00jowe",
    "jowett-brooks-by-way": "brooksbytheway00jowe",
    "jefferson-cardinal-ideas": "cardinalideasof00jeff",
    "jefferson-cardinal-ideas-jeremiah": "cardinalideasje00jeff",
    "stalker-trial-jesus": "trialanddeathof00stal",
    "mcintyre-hidden-life-prayer": "hiddenlifeofpray00mcin",
    "gordon-ministry-spirit": "ministryofspirit00gord",
    "gordon-twofold-life": "twofoldlife00gord",
    "gordon-in-christ": "inchrist00gord",
    "talmage-sermons-v2": "sermonsoftwdewit02talm",
    "simpson-fullness-christ": "fullnessofchrist00simp",
    "simpson-gospel-healing": "gospelofhealing00simp",
    "simpson-wholly-sanctified": "whollysanctified00simp",
    "simpson-days-of-heaven": "daysofheavenupon00simp",
    "trumbull-taking-men-alive": "takingmenalive00trum",
    "trumbull-victory-life": "lifethatwins00trum",
    "pierson-acts-holy-spirit": "actsofholyspirit00pier",
    "andrew-bonar-diary": "diaryandlifeofan00bona",
    "torrey-divine-healing": "divinehealing00torr",
    "torrey-what-bible-teaches": "whatbibleteaches00torr",
    "torrey-how-to-obtain-fullness": "howtoobtainfull00torr",
    "havergal-morning-stars": "morningstars00have",
    "havergal-morning-bells": "morningbells00have",
    "carmichael-gold-cord": "goldcord00carm",
    "carmichael-if": "if00carm",
    "carmichael-rose-from-brier": "rosefrombrier00carm",
    "huegel-bone-of-his-bone": "boneofhisbone00hueg",
    "nee-sit-walk-stand": "sitwalkstand00neew",
    "nee-release-of-spirit": "releaseofspirit00neew",
    "thomas-daily-readings": "dailyreadings00thom",
    "meyer-five-musts": "fivemusts00meye",
    "meyer-joshua-and-land-promise": "joshuaandlandof00meye",
    "meyer-david": "davidshepher00meye",
    "meyer-paul": "paulservantofje00meye",
    "meyer-abraham": "abrahamorobedi00meye",
    "meyer-peter": "peterfishermand00meye",
    "meyer-joseph": "josephbelovedhated00meye",
    "pierson-bible-and-spiritual-life": "bibleandspiritu00pier",
    "pentecost-in-burning-bush": "involumeof00pent",
    "turretin-institutes-sel": "institutesofelen01turr",
    "witsius-economy-covenants-sel": "economyofcovena01wits",
    "vermigli-commonplaces-sel": "commonplaces00verm",
    "bucer-true-pastoral-care": "concerningtrueca00buce",
    "bullinger-decades-sel": "decades01bull",
    "martyn-journals-sel": "journalsandlette00mart",
    "duff-alexander-life": "lifeofalexander00smit",
    "hannington-bishop-last-journals": "lastjournalsofbi00hann",
    "grenfell-labrador": "labradordoctor00gren",
    "elliot-jim-story": "throughgatesofsp00elli",
    "gilmour-among-mongols": "amongmongols00gilm",
    "coillard-on-threshold-africa": "onthresholdofcen00coil",
    "gardiner-allen-biography": "allengardinerpio00mars",
    "stewart-lovedale-south-africa": "lovedalesouthafrica00stew",
    "scudder-nineteen-centuries": "nineteencenturie00scud",
    "zwemer-islam-challenge": "islamachallenge00zwem",
    "verbeck-guido-japan": "guidoverbeckofja00grif",
    "ross-john-korea": "missiontokorea00ross",
    "booth-catherine-female-ministry": "femaleministryor00boot",
    "carmichael-kohila": "kohila00carm",
    "judson-ann-life": "lifeandwritings00know",
    "newell-life-mrs-sherwood": "lifeofmrssherwo00sher",
    "rundle-charles-early-dawn": "earlydawn00char",
    "ridley-havergal-autobiography": "autobiographyand00have",
    "rossetti-face-of-deep": "faceofdeep00ross",
    "catherine-siena-letters-sel": "lettersofcather00cath",
    "elizabeth-seton-sel": "selectedwritings00seto",
    "gertrude-great-herald": "heraldofdivinelo00gert",
    "angela-foligno-memorial": "memorialofangela00ange",
    "marguerite-porete-mirror-sel": "mirrorofsimpleso00mare",
    "hadewijch-visions-sel": "visionsandletter00hade",
    "beatrice-nazareth-seven-manners": "sevenmanner00beat",
    "orr-christian-view-god": "christianviewofg00orrj",
    "orr-problem-ot": "problemofoldtest00orrj",
    "orr-resurrection-jesus": "resurrectionofje00orrj",
    "kuyper-encyclopedia-sel": "encyclopediaofsa00kuyp",
    "kierkegaard-fear-trembling": "fearandtrembling00kier",
    "kierkegaard-sickness-unto-death": "sicknessuntodeat00kier",
    "kierkegaard-attack-christendom": "attackuponchrist00kier",
    "mozley-lectures-miracles": "lecturesonmiracl00mozl",
    "mansel-limits-religious-thought": "limitsofreligi00mans",
    "caird-evolution-religion": "evolutionofrel01cair",
    "illingworth-personality": "personalityhuman00illi",
    "sankey-gospel-hymns": "gospelhymnssacre00sank",
    "sankey-my-life-sacred-song": "mylifeandstor00sank",
    "terstegen-spiritual-songs-sel": "spiritualsongs00ters",
    "zinzendorf-hymns-sel": "hymnsandpoems00zinz",
    "smart-jubilate-agno-sel": "jubilateagno00smar",
    "gale-vanguard": "vanguardtaleofko00gale",
    "gale-korea-in-transition": "koreaintransit00gale",
    "hulbert-passing-of-korea": "passingofkorea00hulb",
    "hulbert-history-korea": "historyofkorea01hulb",
    "jones-george-heber-korea": "korealandpeople00jone",
    "baird-fifty-years-korea": "fiftyyearsinkor00bair",
    "moffett-samuel-korean-mission": "christiansofkore00moff",
    "blair-william-gold-in-korea": "goldinkorea00blai",
    "morrison-memoirs": "memoirsoflifeofrob01morr",
    "medhurst-china": "chinaitsstateand00medh",
    "nevius-demon-possession": "demonpossession00nevi",
    "williams-middle-kingdom-sel": "middlekingdom01will",
    "verbeck-history-japan-protestant": "historyofprotestant00verb",
    "kagawa-before-dawn": "beforethedawn00kaga",
    "kagawa-brotherhood-economics": "brotherhoodecono00kaga",
    "laufer-christian-movement-japan": "christianmovemen00lauf",
    "swallen-william-baird-korea": "williammbairdof00swal",
    "korean-revival-1907": "koreanpentecost00blai",
    "bede-homilies-sel": "bede_homilies",
    "isidore-seville-etymologies-sel": "etymologies00isid",
    "alcuin-letters-sel": "lettersalcuin00alcu",
    "peter-damian-letters-sel": "lettersofdamian00pete",
    "abelard-yes-no-sel": "sicetnon00abel",
    "abelard-ethics": "ethicsscitoteip00abel",
    "william-st-thierry-golden-epistle": "goldenepistle00will",
    "richard-st-victor-trinity": "ontrinitydevict00rich",
    "richard-st-victor-twelve-patriarchs": "twelvepat00rich",
    "duns-scotus-sel": "selectedphiloso00duns",
    "william-ockham-sel": "selectedphiloso00ockh",
    "thomas-bradwardine-cause-god-sel": "causeofgod00brad",
    "wycliffe-select-english-works": "selectenglishwor00wycl",
    "hus-de-ecclesia-sel": "churchdeeccles00hus_",
    "savonarola-sermons-sel": "selectedsermons00savo",
    "groote-following-christ": "followingofchris00groo",
    "gerson-consolation-theology-sel": "consolationtheo00gers",
    "nicolas-cusa-vision-god": "visionofgod00nico",
    "dominic-letters-sel": "selectedletters00domi",
    "francis-de-sales-devout-life": "introductiontode00fran",
    "reid-common-sense-sel": "inquiryintohumanm00reid",
    # Spurgeon MTP / New Park Street from Archive
    "spurgeon-sermons-v4": "metropolitantab04spur",
    "spurgeon-sermons-v5": "metropolitantab05spur",
    "spurgeon-sermons-v6": "metropolitantab06spur",
    "spurgeon-sermons-v7": "metropolitantab07spur",
    "spurgeon-sermons-v8": "metropolitantab08spur",
    "spurgeon-sermons-v9": "metropolitantab09spur",
    "spurgeon-sermons-v10": "metropolitantab10spur",
    "spurgeon-sermons-v11": "metropolitantab11spur",
    "spurgeon-sermons-v12": "metropolitantab12spur",
    "spurgeon-sermons-v13": "metropolitantab13spur",
    "spurgeon-sermons-v14": "metropolitantab14spur",
    "spurgeon-sermons-v15": "metropolitantab15spur",
    "spurgeon-new-park-v1": "newparkstreetpul01spur",
    "spurgeon-new-park-v2": "newparkstreetpul02spur",
    "spurgeon-new-park-v3": "newparkstreetpul03spur",
    "spurgeon-new-park-v4": "newparkstreetpul04spur",
    "spurgeon-new-park-v5": "newparkstreetpul05spur",
    "spurgeon-new-park-v6": "newparkstreetpul06spur",
    "spurgeon-flowers-garden": "flowersfrompurit00spur",
    "spurgeon-autobiography-v1": "autobiography01spur",
    "spurgeon-autobiography-v2": "autobiography02spur",
    "spurgeon-types-and-emblems": "typesandemblems00spur",
    "spurgeon-sword-and-trowel-sel": "swordandtrowel00spur",
    "spurgeon-words-of-wisdom": "wordsofwisdom00spur",
    "spurgeon-devotional-classics": "devotionalclassi00spur",
    "spurgeon-metropolitan-tabernacle": "metropolitantabe00spur",
    # JFB from CCEL/Archive
    "jfb-genesis": "jfb01",
    "jfb-exodus": "jfb01",
    "jfb-leviticus-numbers": "jfb01",
    "jfb-deuteronomy-joshua": "jfb01",
    "jfb-judges-ruth-samuel": "jfb02",
    "jfb-kings-chronicles": "jfb02",
    "jfb-ezra-esther": "jfb02",
    "jfb-job": "jfb03",
    "jfb-psalms": "jfb03",
    "jfb-proverbs-ecclesiastes": "jfb03",
    "jfb-isaiah": "jfb04",
    "jfb-jeremiah-lamentations": "jfb04",
    "jfb-ezekiel-daniel": "jfb04",
    "jfb-minor-prophets": "jfb04",
    "jfb-matthew": "jfb05",
    "jfb-mark-luke": "jfb05",
    "jfb-john": "jfb06",
    "jfb-acts": "jfb06",
    "jfb-romans": "jfb06",
    "jfb-corinthians": "jfb06",
    "jfb-galatians-philemon": "jfb06",
    "jfb-hebrews-revelation": "jfb06",
    # K&D from Archive
    "kd-genesis": "commentaryonoldt01keil",
    "kd-exodus-leviticus": "commentaryonoldt02keil",
    "kd-numbers-deuteronomy": "commentaryonoldt03keil",
    "kd-joshua-judges-ruth": "commentaryonoldt04keil",
    "kd-samuel": "commentaryonoldt05keil",
    "kd-kings": "commentaryonoldt06keil",
    "kd-chronicles-ezra-nehemiah": "commentaryonoldt07keil",
    "kd-esther-job": "commentaryonoldt08keil",
    "kd-psalms": "commentaryonoldt09keil",
    "kd-proverbs-song": "commentaryonoldt10keil",
    "kd-isaiah": "commentaryonoldt11keil",
    "kd-jeremiah-lamentations": "commentaryonoldt12keil",
    "kd-ezekiel-daniel": "commentaryonoldt13keil",
    "kd-minor-prophets": "commentaryonoldt14keil",
    # Ellicott from Archive
    "ellicott-matthew": "ellicottscomment01elli",
    "ellicott-mark-luke": "ellicottscomment02elli",
    "ellicott-john-acts": "ellicottscomment03elli",
    "ellicott-romans-corinthians": "ellicottscomment04elli",
    "ellicott-galatians-thessalonians": "ellicottscomment05elli",
    "ellicott-timothy-revelation": "ellicottscomment06elli",
    # Expositor's Bible from Archive
    "expositors-bible-genesis": "expositorsbible00dods",
    "expositors-bible-exodus": "expositorsbible00rawl",
    "expositors-bible-psalms": "expositorsbible00macl",
    "expositors-bible-isaiah": "expositorsbible00smit",
    "expositors-bible-john": "expositorsbible01dods",
    "expositors-bible-acts": "expositorsbible00stok",
    "expositors-bible-romans": "expositorsbible00moul",
    "expositors-bible-corinthians": "expositorsbible02dods",
    "expositors-bible-ephesians": "expositorsbible00find",
    "expositors-bible-hebrews": "expositorsbible00edwa",
    "expositors-bible-revelation": "expositorsbible00mill",
    # Gill from CCEL/Archive
    "gill-commentary-genesis": "commentaryonold01gill",
    "gill-commentary-psalms-sel": "commentaryonold02gill",
    "gill-commentary-isaiah-sel": "commentaryonold03gill",
    "gill-commentary-matthew": "commentaryonnew01gill",
    "gill-commentary-john": "commentaryonnew02gill",
    "gill-commentary-acts": "commentaryonnew03gill",
    "gill-commentary-hebrews": "commentaryonnew04gill",
    "gill-commentary-revelation": "commentaryonnew05gill",
    # Clarke/Poole/Luther from Archive
    "clarke-commentary-sel-v1": "adamclarkecomment01clar",
    "poole-annotations-sel-v1": "annotationsuponho01pool",
    "poole-annotations-sel-v2": "annotationsuponho02pool",
    "poole-annotations-sel-nt": "annotationsuponho03pool",
    "luther-commentary-romans-sel": "lecturesonromans00luth",
    # Additional reformed/puritan
    "rutherford-letters-v1": "lettersofsamu01ruth",
    "rutherford-letters-v2": "lettersofsamu02ruth",
    "rutherford-lex-rex-sel": "lexrexorthelaw00ruth",
    "owen-hebrews-sel-v1": "expositionofheb01owen",
    "owen-hebrews-sel-v2": "expositionofheb02owen",
    "love-christopher-scottish-worthies": "scottishworthies00howi",
    # Other misc Archive
    "wilberforce-abolition-slave-trade": "letteronaboliti00wilb",
    "elizabeth-charles-chronicles-schonberg": "chroniclesofschon00char",
    "edersheim-sketches-jewish": "sketchesofjewish00eder",
    "oden-care-of-souls-sel": "careofsouls00oden",
    "paisius-velichkovsky-sel": "selectedwritings00pais",
    "hesychius-jerusalem-sel": "onwatchfulness00hesy",
    "desert-mothers-sel": "sayingsofdesertm00swan",
    "bonar-god-plan-sel": "godswayofpeace00bona",
    "bonar-night-of-weeping": "nightofweeping00bona",
    "bonar-words-old-to-young": "wordstothe00bona",
    "bliss-philip-gospel-songs": "gospelsongs00blis",
    "montgomery-hymns": "poeticalworksja00mont",
    "baxter-poetical-fragments": "poeticalfragment00baxt",
    "crashaw-poems-sel": "sacredpoems00cras",
    "vaughan-poems-sel": "silexscintillans00vaug",
    "traherne-centuries-sel": "centuriesofmedit00trah",
    "james-william-varieties-rel": "varietiesofrelig00jame",
}


def ccel_url(path):
    """CCEL 경로에서 URL 구성."""
    if "/" in path:
        # e.g. "spurgeon/treasury7" -> ccel/s/spurgeon/treasury7/...
        parts = path.split("/")
        author = parts[0]
        work = parts[1]
        return f"https://ccel.org/ccel/{author[0]}/{author}/{work}/cache/{work}.txt"
    else:
        # e.g. "npnf201" -> ccel/s/schaff/npnf201/...
        return f"https://ccel.org/ccel/s/schaff/{path}/cache/{path}.txt"


def gutenberg_url(gid):
    return f"https://www.gutenberg.org/cache/epub/{gid}/pg{gid}.txt"


def archive_url(aid):
    return f"https://archive.org/download/{aid}/{aid}_djvu.txt"


def parse_catalog():
    """카탈로그 마크다운에서 도서 목록 파싱."""
    text = CATALOG.read_text(encoding="utf-8")
    # 테이블 행 파싱: | # | slug | 영문 제목 | 한국어 제목 | 저자 | 사망 | 챕터 | 소스 |
    pattern = re.compile(
        r"\|\s*(\d+)\s*\|\s*([a-z0-9-]+)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|"
    )
    books = []
    for m in pattern.finditer(text):
        num = int(m.group(1))
        slug = m.group(2).strip()
        title_en = m.group(3).strip()
        title_kr = m.group(4).strip()
        author = m.group(5).strip()
        death_year = m.group(6).strip()
        chapters = int(m.group(7))
        source = m.group(8).strip()
        books.append({
            "num": num,
            "slug": slug,
            "title_en": title_en,
            "title_kr": title_kr,
            "author": author,
            "death_year": death_year,
            "chapters": chapters,
            "source": source,
        })
    return books


def determine_source_type(source_str):
    """소스 문자열에서 source_type 결정."""
    s = source_str.lower()
    if "ccel" in s and "gutenberg" not in s and "archive" not in s:
        return "ccel"
    if "gutenberg" in s and "ccel" not in s and "archive" not in s:
        return "gutenberg"
    if "archive" in s and "ccel" not in s and "gutenberg" not in s:
        return "archive"
    # 복합 소스: 우선순위 결정
    if "ccel" in s:
        return "ccel"
    if "gutenberg" in s:
        return "gutenberg"
    return "archive"


def resolve_url(slug, source_type):
    """slug과 source_type으로 URL 결정."""
    # CCEL paths
    if slug in CCEL_PATHS:
        return ccel_url(CCEL_PATHS[slug])
    # Gutenberg IDs
    if slug in GUTENBERG_IDS:
        return gutenberg_url(GUTENBERG_IDS[slug])
    # Archive IDs
    if slug in ARCHIVE_IDS:
        return archive_url(ARCHIVE_IDS[slug])
    # JFB CCEL fallback
    if slug.startswith("jfb-"):
        return ccel_url(f"jamieson/jfb")
    # Fallback: construct best guess
    if source_type == "ccel":
        # Try to guess CCEL path from slug
        return f"https://ccel.org/ccel/{slug.replace('-', '/')}"
    elif source_type == "gutenberg":
        return f"https://www.gutenberg.org/ebooks/search/?query={slug.replace('-', '+')}"
    else:
        return f"https://archive.org/download/{slug}/{slug}_djvu.txt"


def make_author_kr(author_en):
    """영어 저자명을 한국어로 변환 (간단 매핑)."""
    MAP = {
        "Eusebius of Caesarea": "가이사랴의 에우세비우스",
        "Socrates Scholasticus": "소크라테스 스콜라스티쿠스",
        "Sozomen": "소조멘",
        "Theodoret": "테오도렛",
        "Sulpicius Severus": "술피키우스 세베루스",
        "Venerable Bede": "존경하는 베다",
        "Adam of Bremen": "브레멘의 아담",
        "William of Malmesbury": "맬름즈베리의 윌리엄",
        "J.H. Merle d'Aubigné": "도비녜",
        "John Lothrop Motley": "존 로드롭 모틀리",
        "J.A. Wylie": "와일리",
        "Philip Schaff": "필립 샤프",
        "K.S. Latourette": "라투렛",
        "Johann Heinrich Kurtz": "쿠르츠",
        "Augustus Neander": "네안더",
        "Henry Hart Milman": "밀만",
        "George Park Fisher": "피셔",
        "Adolf von Harnack": "하르낙",
        "James C. Robertson": "로버트슨",
        "Arthur P. Stanley": "스탠리",
        "George Waddington": "와딩턴",
        "John A. Broadus": "브로더스",
        "W.D. Killen": "킬렌",
        "Various": "다수 저자",
        "Anonymous": "익명",
        "George MacDonald": "조지 맥도널드",
        "Charles M. Sheldon": "찰스 셸던",
        "Lew Wallace": "루 월리스",
        "Henryk Sienkiewicz": "시엔키에비치",
        "Charles Kingsley": "찰스 킹슬리",
        "Charlotte M. Yonge": "샬롯 영",
        "J.H. Ingraham": "인그라함",
        "Elizabeth Rundle Charles": "엘리자벳 런들 찰스",
        "Elizabeth Stuart Phelps": "엘리자벳 스튜어트 펠프스",
        "Dinah Mulock Craik": "다이나 뮬록 크레이크",
        "Marie Corelli": "마리 코렐리",
        "J.H. Shorthouse": "쇼트하우스",
        "Cardinal Wiseman": "위즈먼 추기경",
        "John Henry Newman": "존 헨리 뉴먼",
        "Alfred Edersheim": "에더샤임",
        "John Bunyan": "존 번연",
        "William Wilberforce": "윌리엄 윌버포스",
        "Walter Rauschenbusch": "라우셴부쉬",
        "Washington Gladden": "글래든",
        "Josiah Strong": "조사이어 스트롱",
        "Shailer Mathews": "셰일러 매튜스",
        "Francis Greenwood Peabody": "피바디",
        "Abraham Kuyper": "아브라함 카이퍼",
        "F.D. Maurice": "모리스",
        "Charles Gore (ed.)": "찰스 고어",
        "Albrecht Ritschl": "리츨",
        "P.T. Forsyth": "포사이스",
        "Richard T. Ely": "엘리",
        "A.C. Headlam": "헤들람",
        "Henry Drummond": "헨리 드러먼드",
        "Charles Bridges": "찰스 브리지스",
        "Richard Baxter": "리처드 백스터",
        "Ichabod Spencer": "이카보드 스펜서",
        "Patrick Fairbairn": "패트릭 페어번",
        "James W. Alexander": "제임스 알렉산더",
        "Daniel P. Kidder": "키더",
        "W.G.T. Shedd": "셰드",
        "Thomas Murphy": "토마스 머피",
        "Alexandre Vinet": "비네",
        "Gregory / Chrysostom": "그레고리 / 크리소스톰",
        "C.H. Spurgeon": "C.H. 스펄전",
        "R.L. Dabney": "대브니",
        "Austin Phelps": "오스틴 펠프스",
        "John Watson (Ian Maclaren)": "존 왓슨",
        "John Henry Jowett": "존 헨리 주엣",
        "Charles E. Jefferson": "찰스 제퍼슨",
        "John Oman": "존 오만",
        "Frederic W. Farrar": "파라",
        "Conybeare & Howson": "코니베어 & 하우슨",
        "J.B. Lightfoot": "라이트풋",
        "William M. Ramsay": "램지",
        "Henry Preserved Smith": "스미스",
        "Flavius Josephus": "플라비우스 요세푸스",
        "Justin Martyr": "유스티누스",
        "Tatian": "타티안",
        "Athenagoras": "아테나고라스",
        "Clement of Alexandria": "알렉산드리아의 클레멘트",
        "Tertullian": "테르툴리아누스",
        "Minucius Felix": "미누키우스 펠릭스",
        "Commodianus": "코모디아누스",
        "Hippolytus": "히폴리투스",
        "Novatian": "노바티아누스",
        "Gregory Thaumaturgus": "기적의 그레고리",
        "Dionysius": "디오니시우스",
        "Methodius": "메토디우스",
        "Arnobius": "아르노비우스",
        "Lactantius": "락탄티우스",
        "Venantius": "베난티우스",
        "Pseudo-Clement": "위(僞)클레멘트",
        "Augustine": "아우구스티누스",
        "John Chrysostom": "요한 크리소스톰",
        "Eusebius": "에우세비우스",
        "Socrates/Sozomen": "소크라테스/소조멘",
        "Athanasius": "아타나시우스",
        "Gregory of Nyssa": "닛사의 그레고리",
        "Jerome": "제롬",
        "Cyril/Gregory": "키릴/나지안주스 그레고리",
        "Basil the Great": "대 바실",
        "Hilary of Poitiers": "푸아티에의 힐라리",
        "John of Damascus": "다마스쿠스의 요한",
        "Ambrose": "암브로시우스",
        "G. Campbell Morgan": "캠벨 모건",
        "Joseph Parker": "조셉 파커",
        "Arthur T. Pierson": "피어슨",
        "A.B. Simpson": "심슨",
        "G.A. Chadwick": "채드윅",
        "Marcus Dods": "마커스 도즈",
        "R.W. Dale": "데일",
        "H.P. Liddon": "리든",
        "Alexander Maclaren": "알렉산더 맥클라렌",
        "Handley C.G. Moule": "모울",
        "Alexander Whyte": "알렉산더 화이트",
        "James Stalker": "제임스 스토커",
        "David M. McIntyre": "맥인타이어",
        "A.J. Gordon": "A.J. 고든",
        "T. DeWitt Talmage": "탈마지",
        "E.M. Bounds": "E.M. 바운즈",
        "S.D. Gordon": "S.D. 고든",
        "Andrew Murray": "앤드류 머레이",
        "Charles G. Trumbull": "트럼불",
        "Marjory Bonar (ed.)": "보나르",
        "R.M. M'Cheyne": "맥체인",
        "R.A. Torrey": "R.A. 토레이",
        "Frances Ridley Havergal": "하버갈",
        "Hannah Whitall Smith": "한나 위탈 스미스",
        "Amy Carmichael": "에이미 카마이클",
        "F.J. Huegel": "휴겔",
        "Watchman Nee": "워치만 니",
        "W.H. Griffith Thomas": "그리피스 토마스",
        "F.B. Meyer": "F.B. 마이어",
        "D.L. Moody": "D.L. 무디",
        "George F. Pentecost": "펜테코스트",
        "John Knox et al.": "존 녹스 외",
        "Independents": "독립파",
        "Particular Baptists": "특수 침례파",
        "Church of England": "영국 성공회",
        "James Ussher": "어셔",
        "Lutheran Theologians": "루터파 신학자들",
        "William Ames": "윌리엄 에임스",
        "Francis Turretin": "프란시스 투레틴",
        "Herman Witsius": "헤르만 위치우스",
        "Zacharias Ursinus": "자카리아스 우르시누스",
        "Peter Martyr Vermigli": "베르밀리",
        "Martin Bucer": "마르틴 부처",
        "Heinrich Bullinger": "불링거",
        "Theodore Beza": "테오도르 베자",
        "John Owen": "존 오웬",
        "Thomas Goodwin": "토마스 굿윈",
        "Samuel Rutherford": "사무엘 러더포드",
        "Thomas Shepard": "토마스 셰퍼드",
        "Thomas Brooks": "토마스 브룩스",
        "Stephen Charnock": "스티븐 차녹",
        "John Flavel": "존 플라벨",
        "Thomas Watson": "토마스 왓슨",
        "Thomas Boston": "토마스 보스톤",
        "Richard Sibbes": "리처드 시브스",
        "Jeremiah Burroughs": "예레미야 버로우즈",
        "Thomas Manton": "토마스 맨턴",
        "William Perkins": "윌리엄 퍼킨스",
        "John Howie": "존 하우이",
        "Henry Martyn": "헨리 마틴",
        "George Smith": "조지 스미스",
        "E.C. Dawson": "도슨",
        "Wilfred Grenfell": "그렌펠",
        "Elisabeth Elliot": "엘리자벳 엘리엇",
        "James Gilmour": "제임스 길모어",
        "François Coillard": "코이야르",
        "John W. Marsh": "마쉬",
        "James Stewart": "제임스 스튜어트",
        "Doremus Scudder": "스커더",
        "Samuel Zwemer": "즈웨머",
        "William Elliot Griffis": "그리피스",
        "John Ross": "존 로스",
        "Catherine Booth": "캐서린 부스",
        "Madame Guyon": "기용 부인",
        "James D. Knowles": "놀즈",
        "Mrs. Sherwood": "셔우드 부인",
        "Christina Rossetti": "크리스티나 로세티",
        "Catherine of Siena": "시에나의 카타리나",
        "Julian of Norwich": "노리치의 줄리안",
        "Elizabeth Ann Seton": "엘리자벳 시튼",
        "Gertrude the Great": "대 게르투르드",
        "Angela of Foligno": "폴리뇨의 안젤라",
        "Marguerite Porete": "마르그리트 포레트",
        "Hadewijch": "하데비히",
        "Beatrice of Nazareth": "나자렛의 베아트리스",
        "James Orr": "제임스 오르",
        "G.K. Chesterton": "G.K. 체스터턴",
        "Blaise Pascal": "블레즈 파스칼",
        "Soren Kierkegaard": "쇠렌 키르케고르",
        "J.B. Mozley": "모즐리",
        "Henry Longueville Mansel": "맨셀",
        "William James": "윌리엄 제임스",
        "Edward Caird": "에드워드 케어드",
        "J.R. Illingworth": "일링워스",
        "Thomas Reid": "토마스 리드",
        "Ira D. Sankey": "생키",
        "Horatius Bonar": "호라티우스 보나르",
        "Philip Bliss": "필립 블리스",
        "James Montgomery": "제임스 몽고메리",
        "Gerhard Tersteegen": "테르슈테겐",
        "Nikolaus von Zinzendorf": "진첸도르프",
        "John Milton": "존 밀턴",
        "Richard Crashaw": "리처드 크래쇼",
        "Henry Vaughan": "헨리 보언",
        "Thomas Traherne": "토마스 트라헌",
        "Christopher Smart": "크리스토퍼 스마트",
        "Francis Thompson": "프란시스 톰슨",
        "Gerard Manley Hopkins": "제라드 맨리 홉킨스",
        "John Greenleaf Whittier": "휘티어",
        "James Scarth Gale": "제임스 게일",
        "Homer B. Hulbert": "헐버트",
        "George Heber Jones": "조지 존스",
        "Samuel A. Moffett": "사무엘 모펫",
        "William Blair": "윌리엄 블레어",
        "F.A. McKenzie": "매켄지",
        "E. Morrison": "모리슨",
        "W.H. Medhurst": "메드허스트",
        "John L. Nevius": "네비우스",
        "S. Wells Williams": "윌리엄스",
        "Toyohiko Kagawa": "가가와 도요히코",
        "W.N. Blair / Various": "블레어 외",
        "Jamieson, Fausset, Brown": "제이미슨, 포셋, 브라운",
        "Keil & Delitzsch": "카일 & 델리치",
        "Charles J. Ellicott": "엘리콧",
        "G. Rawlinson": "롤린슨",
        "George Adam Smith": "조지 아담 스미스",
        "G.T. Stokes": "스토크스",
        "G.G. Findlay": "핀들레이",
        "T.C. Edwards": "에드워즈",
        "W. Milligan": "밀리건",
        "John Calvin": "존 칼빈",
        "Martin Luther": "마르틴 루터",
        "Matthew Poole": "매튜 풀",
        "John Gill": "존 길",
        "Adam Clarke": "아담 클라크",
        "John Climacus": "클리마쿠스의 요한",
        "Evagrius Ponticus": "에바그리우스",
        "Dorotheos of Gaza": "가자의 도로테우스",
        "Palladius": "팔라디우스",
        "Isaac the Syrian": "시리아의 이삭",
        "Pachomius": "파코미우스",
        "Maximus the Confessor": "막시무스 증거자",
        "Symeon the New Theologian": "새 신학자 시메온",
        "Gregory Palamas": "그레고리 팔라마스",
        "Ephrem the Syrian": "시리아의 에프라임",
        "Cyril of Jerusalem": "예루살렘의 키릴",
        "Cyril of Alexandria": "알렉산드리아의 키릴",
        "Pseudo-Dionysius": "위(僞)디오니시우스",
        "Theophan the Recluse": "은둔자 테오판",
        "Tikhon of Zadonsk": "자돈스크의 티혼",
        "John of Kronstadt": "크론슈타트의 요한",
        "Ignatius Brianchaninov": "이그나티우스 브랸차니노프",
        "Nil Sorsky": "닐 소르스키",
        "Seraphim of Sarov": "사로프의 세라핌",
        "Paisius Velichkovsky": "파이시우스 벨리츠코프스키",
        "Hesychius of Jerusalem": "예루살렘의 헤시키우스",
        "Venerable Bede": "존경하는 베다",
        "Isidore of Seville": "세비야의 이시도루스",
        "Alcuin of York": "요크의 알쿠인",
        "Peter Damian": "페트루스 다미아니",
        "Peter Abelard": "피에르 아벨라르",
        "William of St. Thierry": "상 티에리의 윌리엄",
        "Richard of St. Victor": "상 빅토르의 리차드",
        "Duns Scotus": "둔스 스코투스",
        "William of Ockham": "오컴의 윌리엄",
        "Thomas Bradwardine": "토마스 브래드워딘",
        "John Wycliffe": "존 위클리프",
        "Jan Hus": "얀 후스",
        "Girolamo Savonarola": "사보나롤라",
        "Gerard Groote": "게라르드 그로테",
        "Jean Gerson": "장 제르송",
        "Nicholas of Cusa": "쿠자누스",
        "Dominic / Dominicans": "도미니크 / 도미니크회",
        "Francis de Sales": "프란치스코 드 살",
        "Nestor": "네스토르",
    }
    return MAP.get(author_en, author_en)


def make_note(slug, title_kr, title_en, author):
    """간단한 설명 생성."""
    return f"{title_kr}. {author}의 저작."


def main():
    # p3a slugs 로드
    p3a = json.loads(P3A.read_text())
    p3a_slugs = set(b["slug"] for b in p3a)
    print(f"p3a: {len(p3a_slugs)}권 제외")

    # 카탈로그 파싱
    books = parse_catalog()
    print(f"카탈로그 파싱: {len(books)}권")

    # p3a 제외
    remaining = [b for b in books if b["slug"] not in p3a_slugs]
    print(f"p3b 대상: {len(remaining)}권")

    # 매니페스트 생성
    manifest = []
    for b in remaining:
        source_type = determine_source_type(b["source"])
        url = resolve_url(b["slug"], source_type)
        author_kr = make_author_kr(b["author"])

        entry = {
            "slug": b["slug"],
            "title": b["title_kr"],
            "title_en": b["title_en"],
            "author_kr": author_kr,
            "author_en": b["author"],
            "year": b["death_year"],
            "url": url,
            "source_type": source_type,
            "note": make_note(b["slug"], b["title_kr"], b["title_en"], author_kr),
        }
        manifest.append(entry)

    # 저장
    OUT.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\n✅ {OUT} 생성 완료: {len(manifest)}권")

    # 소스 타입별 통계
    from collections import Counter
    types = Counter(b["source_type"] for b in manifest)
    print(f"소스별: {dict(types)}")

    # URL 미해결 항목
    unresolved = [b for b in manifest if "search" in b["url"] or b["url"].startswith("https://ccel.org/ccel/")]
    if unresolved:
        print(f"\n⚠️ URL 미해결: {len(unresolved)}권")
        for b in unresolved[:10]:
            print(f"  {b['slug']}: {b['url'][:80]}")


if __name__ == "__main__":
    main()
