#!/usr/bin/env python3
"""Phase 5 Batch F: 종교개혁/청교도/영성고전/선교 — 10권."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from pipeline.scripts.phase5_utils import process_all

BOOKS = [
    {
        "slug": "luther-freedom-christian",
        "title": "기독인의 자유",
        "title_en": "The Freedom of a Christian",
        "author_kr": "마르틴 루터",
        "author_en": "Martin Luther",
        "year": 1520,
        "gutenberg_id": 649,
        "note": "루터 종교개혁의 핵심 소논문. 기독인의 자유와 종의 역설을 논함.",
    },
    {
        "slug": "perkins-art-prophesying",
        "title": "예언하는 기술",
        "title_en": "The Art of Prophesying",
        "author_kr": "윌리엄 퍼킨스",
        "author_en": "William Perkins",
        "year": 1592,
        "ccel_author": "perkins_w",
        "ccel_work": "prophecy",
        "note": "청교도 설교학의 기초. 성경 중심 설교 방법론을 체계화한 최초의 설교학 교과서.",
    },
    {
        "slug": "vincent-shorter-catechism",
        "title": "소교리문답 해설",
        "title_en": "The Shorter Catechism Explained",
        "author_kr": "토마스 빈센트",
        "author_en": "Thomas Vincent",
        "year": 1674,
        "ccel_author": "vincent",
        "ccel_work": "short_cat",
        "note": "웨스트민스터 소교리문답의 명쾌한 해설. 개혁주의 신앙의 기초를 평신도도 이해할 수 있게 풀어냄.",
    },
    {
        "slug": "fenelon-christian-perfection",
        "title": "기독교적 완전",
        "title_en": "Christian Perfection",
        "author_kr": "프랑수아 페넬롱",
        "author_en": "François Fénelon",
        "year": 1715,
        "ccel_author": "fenelon",
        "ccel_work": "perfection",
        "note": "카미노의 대주교 페넬롱의 영성 지침서. 하나님 앞에서 완전한 자기 포기와 사랑을 탐구.",
    },
    {
        "slug": "thomas-scott-force-truth",
        "title": "진리의 힘",
        "title_en": "The Force of Truth",
        "author_kr": "토마스 스콧",
        "author_en": "Thomas Scott",
        "year": 1779,
        "ccel_author": "scott_t",
        "ccel_work": "force",
        "note": "소시니안주의에서 복음주의로 돌아온 스콧의 개종 간증. 존 뉴턴의 영향을 받은 회심의 고전.",
    },
    {
        "slug": "meyer-abraham",
        "title": "아브라함: 믿음의 순종",
        "title_en": "Abraham: Or the Obedience of Faith",
        "author_kr": "F.B. 메이어",
        "author_en": "F. B. Meyer",
        "year": 1897,
        "ccel_author": "meyer",
        "ccel_work": "abraham",
        "note": "메이어의 구약 인물 시리즈. 아브라함의 믿음의 여정을 통해 하나님의 인도하심을 묵상.",
    },
    {
        "slug": "meyer-joseph",
        "title": "요셉: 고난이 빚은 인격",
        "title_en": "Joseph: Beloved-Hated-Exalted",
        "author_kr": "F.B. 메이어",
        "author_en": "F. B. Meyer",
        "year": 1897,
        "ccel_author": "meyer",
        "ccel_work": "joseph",
        "note": "메이어의 요셉 이야기 명상. 고난을 통한 하나님의 섭리와 용서의 능력을 탐구.",
    },
    {
        "slug": "chambers-still-higher",
        "title": "더 높은 곳을 향하여",
        "title_en": "Still Higher for His Highest",
        "author_kr": "오스왈드 챔버스",
        "author_en": "Oswald Chambers",
        "year": 1927,
        "note": "오스왈드 챔버스의 주옥 같은 묵상 모음. 《주님은 나의 최고봉》 자매편.",
    },
    {
        "slug": "desales-devout-life",
        "title": "경건한 삶 입문",
        "title_en": "Introduction to the Devout Life",
        "author_kr": "프란체스코 살레시오",
        "author_en": "Francis de Sales",
        "year": 1609,
        "ccel_author": "desales",
        "ccel_work": "devout_life",
        "note": "평신도를 위한 실천적 영성 지침서. 16세기 가톨릭 영성의 보편적 고전.",
    },
    {
        "slug": "taylor-retrospect",
        "title": "허드슨 테일러 회고록",
        "title_en": "A Retrospect",
        "author_kr": "J. 허드슨 테일러",
        "author_en": "J. Hudson Taylor",
        "year": 1894,
        "ccel_author": "taylor_jh",
        "ccel_work": "retrospect",
        "note": "중국 내지 선교회 창설자 허드슨 테일러의 짧은 자서전. 하나님의 신실하심에 대한 생생한 간증.",
    },
]

if __name__ == "__main__":
    process_all(BOOKS, delay=1.5)
