#!/usr/bin/env python3
"""Phase 7 배치 A: 카테고리 66-67 (크리소스톰 강해 12 + 갑바도기아 교부들 10) — 22권."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from pipeline.scripts.phase5_utils import process_all

BOOKS = [
    # ── 카테고리 66: 크리소스톰 성경 강해 (12권) ──
    {
        "slug": "chrysostom-homilies-matthew",
        "title": "마태복음 강해 (90편)",
        "title_en": "Homilies on the Gospel of Matthew (90 Homilies)",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 390,
    },
    {
        "slug": "chrysostom-homilies-john",
        "title": "요한복음 강해 (88편)",
        "title_en": "Homilies on the Gospel of John (88 Homilies)",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 391,
    },
    {
        "slug": "chrysostom-homilies-acts",
        "title": "사도행전 강해 (55편)",
        "title_en": "Homilies on the Acts of the Apostles (55 Homilies)",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 400,
    },
    {
        "slug": "chrysostom-homilies-romans",
        "title": "로마서 강해 (32편)",
        "title_en": "Homilies on Romans (32 Homilies)",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 391,
    },
    {
        "slug": "chrysostom-homilies-1cor",
        "title": "고린도전서 강해 (44편)",
        "title_en": "Homilies on 1 Corinthians (44 Homilies)",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 392,
    },
    {
        "slug": "chrysostom-homilies-2cor",
        "title": "고린도후서 강해 (30편)",
        "title_en": "Homilies on 2 Corinthians (30 Homilies)",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 393,
    },
    {
        "slug": "chrysostom-homilies-galatians-ephesians",
        "title": "갈라디아서·에베소서 강해",
        "title_en": "Homilies on Galatians & Ephesians",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 393,
    },
    {
        "slug": "chrysostom-homilies-philippians-col-thess",
        "title": "빌립보서·골로새서·데살로니가서 강해",
        "title_en": "Homilies on Philippians, Colossians & Thessalonians",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 394,
    },
    {
        "slug": "chrysostom-homilies-hebrews",
        "title": "히브리서 강해 (34편)",
        "title_en": "Homilies on the Epistle to the Hebrews (34 Homilies)",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 403,
    },
    {
        "slug": "chrysostom-on-priesthood",
        "title": "사제직에 관한 여섯 권의 책",
        "title_en": "Six Books on the Priesthood (De Sacerdotio)",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 390,
    },
    {
        "slug": "chrysostom-homilies-statues",
        "title": "동상에 관한 강해 (21편)",
        "title_en": "Homilies on the Statues (21 Homilies)",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 387,
    },
    {
        "slug": "chrysostom-letters-olympias",
        "title": "올림피아스 등에게 보낸 서신집",
        "title_en": "Letters of Chrysostom to Olympias and Others",
        "author_kr": "요한 크리소스톰",
        "author_en": "John Chrysostom",
        "year": 403,
    },
    # ── 카테고리 67: 갑바도기아 교부들 (10권) ──
    {
        "slug": "basil-on-holy-spirit",
        "title": "성령론",
        "title_en": "On the Holy Spirit (De Spiritu Sancto)",
        "author_kr": "가이사랴의 바실리우스",
        "author_en": "Basil of Caesarea",
        "year": 375,
    },
    {
        "slug": "basil-hexaemeron",
        "title": "창조의 6일 강해 (9편)",
        "title_en": "Hexaemeron: Nine Homilies on Creation",
        "author_kr": "가이사랴의 바실리우스",
        "author_en": "Basil of Caesarea",
        "year": 370,
    },
    {
        "slug": "basil-letters-selected",
        "title": "바실리우스 서신집 (선집)",
        "title_en": "Letters of Basil (selections — doctrinal & pastoral)",
        "author_kr": "가이사랴의 바실리우스",
        "author_en": "Basil of Caesarea",
        "year": 370,
    },
    {
        "slug": "basil-ascetical-works",
        "title": "수도 규칙서: 장규·단규",
        "title_en": "The Ascetical Works: Long Rules & Short Rules",
        "author_kr": "가이사랴의 바실리우스",
        "author_en": "Basil of Caesarea",
        "year": 358,
    },
    {
        "slug": "gregory-nyssa-life-of-moses",
        "title": "모세의 생애",
        "title_en": "The Life of Moses (De Vita Moysis)",
        "author_kr": "닛사의 그레고리우스",
        "author_en": "Gregory of Nyssa",
        "year": 390,
    },
    {
        "slug": "gregory-nyssa-great-catechism",
        "title": "대교리 강해",
        "title_en": "The Great Catechetical Oration",
        "author_kr": "닛사의 그레고리우스",
        "author_en": "Gregory of Nyssa",
        "year": 385,
    },
    {
        "slug": "gregory-nyssa-soul-resurrection",
        "title": "영혼과 부활 (마크리나와의 대화)",
        "title_en": "On the Soul and the Resurrection (Macrina Dialogue)",
        "author_kr": "닛사의 그레고리우스",
        "author_en": "Gregory of Nyssa",
        "year": 380,
    },
    {
        "slug": "gregory-nazianzus-theological-orations",
        "title": "신학 강연 5편",
        "title_en": "The Five Theological Orations (Orations 27–31)",
        "author_kr": "나지안주스의 그레고리우스",
        "author_en": "Gregory of Nazianzus",
        "year": 380,
    },
    {
        "slug": "gregory-nazianzus-orations-selected",
        "title": "선집 강연 (부활·오순절·바실리우스 추도사)",
        "title_en": "Selected Orations: On Easter, Pentecost, Basil's Eulogy",
        "author_kr": "나지안주스의 그레고리우스",
        "author_en": "Gregory of Nazianzus",
        "year": 381,
    },
    {
        "slug": "gregory-nazianzus-carmina-sel",
        "title": "시와 자서전적 저술 선집",
        "title_en": "Carmina: Selected Poems and Autobiographical Writings",
        "author_kr": "나지안주스의 그레고리우스",
        "author_en": "Gregory of Nazianzus",
        "year": 382,
    },
]

if __name__ == "__main__":
    process_all(BOOKS)
