#!/usr/bin/env python3
"""Phase 5 Batch A: 카테고리 47-49 (윌리엄 로, 스코틀랜드 언약도, 토마스 왓슨) — 25권."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from pipeline.scripts.phase5_utils import process_all

BOOKS = [
    # ── 카테고리 47: William Law (5권) ──
    {
        "slug": "law-serious-call",
        "title": "경건한 생활에 대한 진지한 권고",
        "title_en": "A Serious Call to a Devout and Holy Life",
        "author_kr": "윌리엄 로",
        "author_en": "William Law",
        "year": 1729,
        "gutenberg_id": 1250,
        "ccel_author": "law",
        "ccel_work": "serious_call",
    },
    {
        "slug": "law-spirit-of-love",
        "title": "사랑의 영",
        "title_en": "The Spirit of Love",
        "author_kr": "윌리엄 로",
        "author_en": "William Law",
        "year": 1752,
    },
    {
        "slug": "law-spirit-of-prayer",
        "title": "기도의 영",
        "title_en": "The Spirit of Prayer",
        "author_kr": "윌리엄 로",
        "author_en": "William Law",
        "year": 1749,
    },
    {
        "slug": "law-christian-perfection",
        "title": "기독교적 완전",
        "title_en": "Christian Perfection",
        "author_kr": "윌리엄 로",
        "author_en": "William Law",
        "year": 1726,
        "ccel_author": "law",
        "ccel_work": "perfection",
    },
    {
        "slug": "law-appeal-to-all",
        "title": "의심하는 모든 이에게",
        "title_en": "An Appeal to All Who Doubt",
        "author_kr": "윌리엄 로",
        "author_en": "William Law",
        "year": 1740,
    },
    # ── 카테고리 48: Samuel Rutherford & Scottish Covenanters (12권) ──
    {
        "slug": "rutherford-letters",
        "title": "새뮤얼 러더퍼드 서신집",
        "title_en": "The Letters of Samuel Rutherford",
        "author_kr": "새뮤얼 러더퍼드",
        "author_en": "Samuel Rutherford",
        "year": 1664,
    },
    {
        "slug": "rutherford-lex-rex",
        "title": "렉스 렉스: 법과 왕",
        "title_en": "Lex Rex The Law and the Prince",
        "author_kr": "새뮤얼 러더퍼드",
        "author_en": "Samuel Rutherford",
        "year": 1644,
    },
    {
        "slug": "rutherford-trial-of-faith",
        "title": "믿음의 시험과 승리",
        "title_en": "The Trial and Triumph of Faith",
        "author_kr": "새뮤얼 러더퍼드",
        "author_en": "Samuel Rutherford",
        "year": 1645,
    },
    {
        "slug": "boston-fourfold-state",
        "title": "인간의 네 가지 상태",
        "title_en": "Human Nature in Its Fourfold State",
        "author_kr": "토마스 보스턴",
        "author_en": "Thomas Boston",
        "year": 1720,
    },
    {
        "slug": "boston-covenant-grace",
        "title": "은혜 언약",
        "title_en": "The Covenant of Grace",
        "author_kr": "토마스 보스턴",
        "author_en": "Thomas Boston",
        "year": 1734,
    },
    {
        "slug": "boston-crook-in-lot",
        "title": "삶 속의 굴곡",
        "title_en": "The Crook in the Lot",
        "author_kr": "토마스 보스턴",
        "author_en": "Thomas Boston",
        "year": 1737,
    },
    {
        "slug": "boston-memoirs",
        "title": "토마스 보스턴 회고록",
        "title_en": "Memoirs of Thomas Boston",
        "author_kr": "토마스 보스턴",
        "author_en": "Thomas Boston",
        "year": 1776,
    },
    {
        "slug": "leighton-commentary-1peter",
        "title": "베드로전서 주석",
        "title_en": "Commentary on First Peter",
        "author_kr": "로버트 레이턴",
        "author_en": "Robert Leighton",
        "year": 1693,
        "ccel_author": "leighton",
        "ccel_work": "firstpeter",
    },
    {
        "slug": "leighton-sermons-select",
        "title": "설교 선집",
        "title_en": "Select Sermons of Robert Leighton",
        "author_kr": "로버트 레이턴",
        "author_en": "Robert Leighton",
        "year": 1693,
    },
    {
        "slug": "dick-lectures-theology",
        "title": "신학 강의",
        "title_en": "Lectures on Theology",
        "author_kr": "존 딕",
        "author_en": "John Dick",
        "year": 1836,
    },
    {
        "slug": "gillespie-aaron-rod",
        "title": "아론의 꽃핀 지팡이",
        "title_en": "Aarons Rod Blossoming",
        "author_kr": "조지 길레스피",
        "author_en": "George Gillespie",
        "year": 1646,
    },
    {
        "slug": "smeaton-doctrine-holy-spirit",
        "title": "성령론",
        "title_en": "The Doctrine of the Holy Spirit",
        "author_kr": "조지 스미턴",
        "author_en": "George Smeaton",
        "year": 1882,
        "ccel_author": "smeaton",
        "ccel_work": "holyspirit",
    },
    # ── 카테고리 49: Thomas Watson (8권) ──
    {
        "slug": "watson-body-of-divinity",
        "title": "신앙의 보고",
        "title_en": "A Body of Divinity",
        "author_kr": "토마스 왓슨",
        "author_en": "Thomas Watson",
        "year": 1692,
        "ccel_author": "watson",
        "ccel_work": "divinity",
    },
    {
        "slug": "watson-lords-prayer",
        "title": "주기도문 강해",
        "title_en": "The Lords Prayer",
        "author_kr": "토마스 왓슨",
        "author_en": "Thomas Watson",
        "year": 1692,
        "ccel_author": "watson",
        "ccel_work": "prayer",
    },
    {
        "slug": "watson-ten-commandments",
        "title": "십계명 강해",
        "title_en": "The Ten Commandments",
        "author_kr": "토마스 왓슨",
        "author_en": "Thomas Watson",
        "year": 1692,
        "ccel_author": "watson",
        "ccel_work": "commandments",
    },
    {
        "slug": "watson-beatitudes",
        "title": "팔복",
        "title_en": "The Beatitudes",
        "author_kr": "토마스 왓슨",
        "author_en": "Thomas Watson",
        "year": 1660,
        "ccel_author": "watson",
        "ccel_work": "beatitudes",
    },
    {
        "slug": "watson-all-things-for-good",
        "title": "만사가 합력하여 선을 이루리라",
        "title_en": "All Things for Good",
        "author_kr": "토마스 왓슨",
        "author_en": "Thomas Watson",
        "year": 1663,
        "ccel_author": "watson",
        "ccel_work": "good",
    },
    {
        "slug": "watson-heaven-taken-by-storm",
        "title": "강력함으로 빼앗는 하늘 나라",
        "title_en": "Heaven Taken by Storm",
        "author_kr": "토마스 왓슨",
        "author_en": "Thomas Watson",
        "year": 1669,
    },
    {
        "slug": "watson-sermon-on-mount",
        "title": "산상수훈 선집 설교",
        "title_en": "Select Sermons of Thomas Watson",
        "author_kr": "토마스 왓슨",
        "author_en": "Thomas Watson",
        "year": 1686,
    },
    {
        "slug": "watson-godly-man-picture",
        "title": "경건한 사람의 모습",
        "title_en": "The Godly Mans Picture",
        "author_kr": "토마스 왓슨",
        "author_en": "Thomas Watson",
        "year": 1666,
        "ccel_author": "watson",
        "ccel_work": "godly",
    },
]

if __name__ == "__main__":
    process_all(BOOKS, delay=1.5)
