#!/usr/bin/env python3
"""Phase 5 Batch D: 카테고리 56-58 (한국선교사료, 아담클라크, 청교도보충) — 40권."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from pipeline.scripts.phase5_utils import process_all

BOOKS = [
    # ── 카테고리 56: Korean Mission Primary Sources (20권) ──
    {
        "slug": "underwood-call-of-korea",
        "title": "한국의 부름",
        "title_en": "The Call of Korea",
        "author_kr": "호레이스 언더우드",
        "author_en": "Horace Grant Underwood",
        "year": 1908,
    },
    {
        "slug": "underwood-korean-language",
        "title": "한국어 입문",
        "title_en": "An Introduction to the Korean Spoken Language",
        "author_kr": "호레이스 언더우드",
        "author_en": "Horace Grant Underwood",
        "year": 1890,
    },
    {
        "slug": "gale-korea-sketches",
        "title": "한국 스케치",
        "title_en": "Korean Sketches",
        "author_kr": "제임스 게일",
        "author_en": "James Scarth Gale",
        "year": 1898,
    },
    {
        "slug": "gale-korea-in-transition",
        "title": "전환기의 한국",
        "title_en": "Korea in Transition",
        "author_kr": "제임스 게일",
        "author_en": "James Scarth Gale",
        "year": 1909,
    },
    {
        "slug": "hulbert-passing-of-korea",
        "title": "한국의 쇠퇴",
        "title_en": "The Passing of Korea",
        "author_kr": "호머 헐버트",
        "author_en": "Homer B. Hulbert",
        "year": 1906,
        "gutenberg_id": 20292,
    },
    {
        "slug": "hulbert-history-korea-v1",
        "title": "한국사 제1권",
        "title_en": "The History of Korea Vol 1",
        "author_kr": "호머 헐버트",
        "author_en": "Homer B. Hulbert",
        "year": 1905,
    },
    {
        "slug": "hulbert-history-korea-v2",
        "title": "한국사 제2권",
        "title_en": "The History of Korea Vol 2",
        "author_kr": "호머 헐버트",
        "author_en": "Homer B. Hulbert",
        "year": 1905,
    },
    {
        "slug": "allen-things-korean",
        "title": "한국에 관한 것들",
        "title_en": "Things Korean",
        "author_kr": "호러스 앨런",
        "author_en": "Horace N. Allen",
        "year": 1908,
    },
    {
        "slug": "baird-inside-views",
        "title": "선교 생활의 내면",
        "title_en": "Inside Views of Mission Life",
        "author_kr": "윌리엄 베어드",
        "author_en": "William M. Baird",
        "year": 1913,
    },
    {
        "slug": "blair-korea-pentecost",
        "title": "한국의 오순절",
        "title_en": "The Korean Pentecost",
        "author_kr": "윌리엄 블레어",
        "author_en": "William Newton Blair",
        "year": 1910,
    },
    {
        "slug": "moffett-letters-korea",
        "title": "한국에서 보내는 편지들",
        "title_en": "Letters from Korea",
        "author_kr": "새뮤얼 모펫",
        "author_en": "Samuel A. Moffett",
        "year": 1907,
    },
    {
        "slug": "methodist-mission-reports",
        "title": "한국 감리교 선교 초기 보고서",
        "title_en": "Methodist Mission in Korea Early Reports",
        "author_kr": "Various",
        "author_en": "Various Methodists",
        "year": 1900,
    },
    {
        "slug": "presbyterian-mission-reports",
        "title": "한국 장로교 선교 현장 보고서",
        "title_en": "Presbyterian Mission in Korea Field Reports",
        "author_kr": "Various",
        "author_en": "Various Presbyterians",
        "year": 1900,
    },
    {
        "slug": "gifford-every-day-life-korea",
        "title": "한국의 일상생활",
        "title_en": "Every-Day Life in Korea",
        "author_kr": "다니엘 기포드",
        "author_en": "Daniel L. Gifford",
        "year": 1898,
    },
    {
        "slug": "jones-george-korea-mission",
        "title": "감리교 한국 선교",
        "title_en": "The Korea Mission of the Methodist Church",
        "author_kr": "조지 존스",
        "author_en": "George H. Jones",
        "year": 1910,
    },
    {
        "slug": "appenzeller-diary",
        "title": "아펜젤러 일기와 서신",
        "title_en": "Appenzellers Diary and Letters",
        "author_kr": "헨리 아펜젤러",
        "author_en": "Henry G. Appenzeller",
        "year": 1902,
    },
    {
        "slug": "scranton-pioneer-medical",
        "title": "한국 선구자 의료 선교",
        "title_en": "Pioneer Medical Work in Korea",
        "author_kr": "메리 스크랜튼",
        "author_en": "Mary Scranton",
        "year": 1910,
    },
    {
        "slug": "bruen-forty-years-korea",
        "title": "한국에서의 40년",
        "title_en": "Forty Years in Korea",
        "author_kr": "헨리 브루엔",
        "author_en": "Henry M. Bruen",
        "year": 1926,
    },
    {
        "slug": "swallen-mission-field-korea",
        "title": "한국 선교 전장 (선집)",
        "title_en": "The Korea Mission Field",
        "author_kr": "Various",
        "author_en": "Various missionaries",
        "year": 1910,
    },
    {
        "slug": "eckardt-korean-church-history",
        "title": "초기 한국 교회사",
        "title_en": "History of the Korean Church",
        "author_kr": "Various",
        "author_en": "Various",
        "year": 1910,
    },
    # ── 카테고리 57: Adam Clarke Commentary (8권) ──
    {
        "slug": "clarke-commentary-ot-v2",
        "title": "아담 클라크 주석: 역사서",
        "title_en": "Adam Clarkes Commentary on the Historical Books",
        "author_kr": "아담 클라크",
        "author_en": "Adam Clarke",
        "year": 1832,
    },
    {
        "slug": "clarke-commentary-ot-v3",
        "title": "아담 클라크 주석: 시가서",
        "title_en": "Adam Clarkes Commentary on the Poetical Books",
        "author_kr": "아담 클라크",
        "author_en": "Adam Clarke",
        "year": 1832,
    },
    {
        "slug": "clarke-commentary-ot-v4",
        "title": "아담 클라크 주석: 대선지서",
        "title_en": "Adam Clarkes Commentary on the Major Prophets",
        "author_kr": "아담 클라크",
        "author_en": "Adam Clarke",
        "year": 1832,
    },
    {
        "slug": "clarke-commentary-ot-v5",
        "title": "아담 클라크 주석: 소선지서",
        "title_en": "Adam Clarkes Commentary on the Minor Prophets",
        "author_kr": "아담 클라크",
        "author_en": "Adam Clarke",
        "year": 1832,
    },
    {
        "slug": "clarke-commentary-nt-v1",
        "title": "아담 클라크 주석: 복음서",
        "title_en": "Adam Clarkes Commentary on the Gospels",
        "author_kr": "아담 클라크",
        "author_en": "Adam Clarke",
        "year": 1832,
    },
    {
        "slug": "clarke-commentary-nt-v2",
        "title": "아담 클라크 주석: 사도행전~로마서",
        "title_en": "Adam Clarkes Commentary on Acts to Romans",
        "author_kr": "아담 클라크",
        "author_en": "Adam Clarke",
        "year": 1832,
    },
    {
        "slug": "clarke-commentary-nt-v3",
        "title": "아담 클라크 주석: 서신서",
        "title_en": "Adam Clarkes Commentary on the Epistles",
        "author_kr": "아담 클라크",
        "author_en": "Adam Clarke",
        "year": 1832,
    },
    {
        "slug": "clarke-commentary-nt-v4",
        "title": "아담 클라크 주석: 요한계시록",
        "title_en": "Adam Clarkes Commentary on Revelation",
        "author_kr": "아담 클라크",
        "author_en": "Adam Clarke",
        "year": 1832,
    },
    # ── 카테고리 58: Puritan Supplementary Works (12권) ──
    {
        "slug": "flavel-mystery-providence",
        "title": "섭리의 신비",
        "title_en": "The Mystery of Providence",
        "author_kr": "존 플래벨",
        "author_en": "John Flavel",
        "year": 1678,
        "ccel_author": "flavel",
        "ccel_work": "providence",
    },
    {
        "slug": "flavel-pneumatologia",
        "title": "영혼론",
        "title_en": "Pneumatologia A Treatise on the Soul",
        "author_kr": "존 플래벨",
        "author_en": "John Flavel",
        "year": 1685,
    },
    {
        "slug": "manton-james-commentary",
        "title": "야고보서 주석",
        "title_en": "Commentary on James",
        "author_kr": "토마스 맨턴",
        "author_en": "Thomas Manton",
        "year": 1651,
    },
    {
        "slug": "manton-hundred-ninety-sermons",
        "title": "설교 선집",
        "title_en": "One Hundred and Ninety Sermons",
        "author_kr": "토마스 맨턴",
        "author_en": "Thomas Manton",
        "year": 1681,
    },
    {
        "slug": "charnock-existence-attributes",
        "title": "하나님의 존재와 속성",
        "title_en": "Discourses on the Existence and Attributes of God",
        "author_kr": "스티븐 차녹",
        "author_en": "Stephen Charnock",
        "year": 1682,
        "ccel_author": "charnock",
        "ccel_work": "attributes",
    },
    {
        "slug": "howe-living-temple",
        "title": "살아 있는 성전",
        "title_en": "The Living Temple",
        "author_kr": "존 하우",
        "author_en": "John Howe",
        "year": 1675,
    },
    {
        "slug": "love-short-catechism",
        "title": "짧은 요리문답과 증명",
        "title_en": "Short Catechism with Proofs",
        "author_kr": "크리스토퍼 러브",
        "author_en": "Christopher Love",
        "year": 1653,
    },
    {
        "slug": "goodwin-heart-of-christ",
        "title": "하늘에 계신 그리스도의 마음",
        "title_en": "The Heart of Christ in Heaven",
        "author_kr": "토마스 굿윈",
        "author_en": "Thomas Goodwin",
        "year": 1651,
        "ccel_author": "goodwin",
        "ccel_work": "heart",
    },
    {
        "slug": "goodwin-object-of-faith",
        "title": "칭의 믿음의 대상과 행위",
        "title_en": "The Object and Acts of Justifying Faith",
        "author_kr": "토마스 굿윈",
        "author_en": "Thomas Goodwin",
        "year": 1680,
    },
    {
        "slug": "brooks-precious-remedies",
        "title": "사탄의 계략에 대한 귀한 처방",
        "title_en": "Precious Remedies Against Satans Devices",
        "author_kr": "토마스 브룩스",
        "author_en": "Thomas Brooks",
        "year": 1652,
        "ccel_author": "brooks",
        "ccel_work": "remedies",
    },
    {
        "slug": "brooks-cabinet-jewels",
        "title": "보석 진열장",
        "title_en": "A Cabinet of Choice Jewels",
        "author_kr": "토마스 브룩스",
        "author_en": "Thomas Brooks",
        "year": 1669,
    },
    {
        "slug": "bolton-last-four-things",
        "title": "볼턴의 마지막 주요 저작",
        "title_en": "Mr Boltons Last and Learned Work",
        "author_kr": "로버트 볼턴",
        "author_en": "Robert Bolton",
        "year": 1632,
    },
]

if __name__ == "__main__":
    process_all(BOOKS, delay=1.5)
