#!/usr/bin/env python3
"""Phase 6 배치 E: 카테고리 56-57 (기독교 시문학, 19세기 위대한 설교가들) — 22권."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from pipeline.scripts.phase5_utils import process_all

BOOKS = [
    # ── 카테고리 56: 기독교 시문학 명저 (8권) ──
    {
        "slug": "herbert-temple",
        "title": "성전: 거룩한 시와 개인 기도",
        "title_en": "The Temple: Sacred Poems and Private Ejaculations",
        "author_kr": "조지 허버트",
        "author_en": "George Herbert",
        "year": 1633,
        "gutenberg_id": 10250,
    },
    {
        "slug": "herbert-country-parson",
        "title": "성직자의 삶",
        "title_en": "A Priest to the Temple (The Country Parson)",
        "author_kr": "조지 허버트",
        "author_en": "George Herbert",
        "year": 1652,
    },
    {
        "slug": "vaughan-silex-scintillans",
        "title": "불꽃 부싯돌 (거룩한 시편)",
        "title_en": "Silex Scintillans (Sacred Poems)",
        "author_kr": "헨리 본",
        "author_en": "Henry Vaughan",
        "year": 1650,
    },
    {
        "slug": "donne-divine-poems",
        "title": "신성한 시와 거룩한 소네트",
        "title_en": "Divine Poems and Holy Sonnets",
        "author_kr": "존 던",
        "author_en": "John Donne",
        "year": 1633,
    },
    {
        "slug": "donne-devotions-emergencies",
        "title": "긴박한 상황을 위한 묵상",
        "title_en": "Devotions upon Emergent Occasions",
        "author_kr": "존 던",
        "author_en": "John Donne",
        "year": 1624,
    },
    {
        "slug": "rossetti-verses",
        "title": "시편: 성인으로 부르심을 받아",
        "title_en": "Verses: Reprinted from Called to be Saints",
        "author_kr": "크리스티나 로세티",
        "author_en": "Christina Rossetti",
        "year": 1893,
    },
    {
        "slug": "thompson-hound-of-heaven",
        "title": "천국의 사냥개와 기타 시",
        "title_en": "The Hound of Heaven and Other Poems",
        "author_kr": "프란시스 톰슨",
        "author_en": "Francis Thompson",
        "year": 1893,
    },
    {
        "slug": "keble-christian-year",
        "title": "기독교의 해",
        "title_en": "The Christian Year",
        "author_kr": "존 케블",
        "author_en": "John Keble",
        "year": 1827,
    },
    # ── 카테고리 57: 19세기 위대한 설교가들 (14권) ──
    {
        "slug": "whyte-bible-characters-v1",
        "title": "성경 인물론 제1권: 아담~아간",
        "title_en": "Bible Characters Vol.1: OT — Adam to Achan",
        "author_kr": "알렉산더 와이트",
        "author_en": "Alexander Whyte",
        "year": 1896,
    },
    {
        "slug": "whyte-bible-characters-v2",
        "title": "성경 인물론 제2권: 기드온~압살롬",
        "title_en": "Bible Characters Vol.2: OT — Gideon to Absalom",
        "author_kr": "알렉산더 와이트",
        "author_en": "Alexander Whyte",
        "year": 1898,
    },
    {
        "slug": "whyte-bible-characters-v3",
        "title": "성경 인물론 제3권: 구약·외경",
        "title_en": "Bible Characters Vol.3: OT & Apocrypha",
        "author_kr": "알렉산더 와이트",
        "author_en": "Alexander Whyte",
        "year": 1900,
    },
    {
        "slug": "whyte-bible-characters-v4",
        "title": "성경 인물론 제4권: 사도들",
        "title_en": "Bible Characters Vol.4: NT — Apostles",
        "author_kr": "알렉산더 와이트",
        "author_en": "Alexander Whyte",
        "year": 1906,
    },
    {
        "slug": "whyte-lord-teach-us-pray",
        "title": "주여, 우리에게 기도를 가르쳐 주소서",
        "title_en": "Lord, Teach Us to Pray",
        "author_kr": "알렉산더 와이트",
        "author_en": "Alexander Whyte",
        "year": 1922,
    },
    {
        "slug": "drummond-greatest-thing",
        "title": "세상에서 가장 위대한 것 (고전 13장)",
        "title_en": "The Greatest Thing in the World",
        "author_kr": "헨리 드럼먼드",
        "author_en": "Henry Drummond",
        "year": 1884,
        "gutenberg_id": 1880,
    },
    {
        "slug": "drummond-natural-law",
        "title": "영적 세계의 자연 법칙",
        "title_en": "Natural Law in the Spiritual World",
        "author_kr": "헨리 드럼먼드",
        "author_en": "Henry Drummond",
        "year": 1883,
        "gutenberg_id": 1372,
    },
    {
        "slug": "drummond-new-evangelism",
        "title": "새 복음전도와 기타 논문",
        "title_en": "The New Evangelism and Other Papers",
        "author_kr": "헨리 드럼먼드",
        "author_en": "Henry Drummond",
        "year": 1899,
    },
    {
        "slug": "matheson-moments-mount",
        "title": "산 위의 순간들",
        "title_en": "Moments on the Mount",
        "author_kr": "조지 매서슨",
        "author_en": "George Matheson",
        "year": 1884,
    },
    {
        "slug": "matheson-studies-portrait-christ",
        "title": "그리스도의 초상 연구",
        "title_en": "Studies of the Portrait of Christ",
        "author_kr": "조지 매서슨",
        "author_en": "George Matheson",
        "year": 1899,
    },
    {
        "slug": "parker-city-temple-v1",
        "title": "시티 템플 설교집 제1권",
        "title_en": "City Temple Sermons Vol.1",
        "author_kr": "조지프 파커",
        "author_en": "Joseph Parker",
        "year": 1886,
    },
    {
        "slug": "parker-city-temple-v2",
        "title": "시티 템플 설교집 제2권",
        "title_en": "City Temple Sermons Vol.2",
        "author_kr": "조지프 파커",
        "author_en": "Joseph Parker",
        "year": 1890,
    },
    {
        "slug": "macgregor-making-of-man",
        "title": "사람의 형성",
        "title_en": "The Making of a Man",
        "author_kr": "W.M. 맥그레거",
        "author_en": "W.M. Macgregor",
        "year": 1927,
    },
    {
        "slug": "jowett-passion-for-souls",
        "title": "영혼을 향한 열정",
        "title_en": "The Passion for Souls",
        "author_kr": "J.H. 조웨트",
        "author_en": "J.H. Jowett",
        "year": 1905,
    },
]

if __name__ == "__main__":
    process_all(BOOKS)
