#!/usr/bin/env python3
"""Phase 5 Batch C: 카테고리 53-55 (하벌갈/여성작가, F.B. 마이어, 휫필드/부흥) — 26권."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from pipeline.scripts.phase5_utils import process_all

BOOKS = [
    # ── 카테고리 53: Frances Ridley Havergal & Women Devotional Writers (8권) ──
    {
        "slug": "havergal-kept-masters-use",
        "title": "주인을 위해 남겨진",
        "title_en": "Kept for the Masters Use",
        "author_kr": "프란체스 릿지 하벌갈",
        "author_en": "Frances Ridley Havergal",
        "year": 1879,
    },
    {
        "slug": "havergal-royal-bounty",
        "title": "왕의 풍성한 은혜",
        "title_en": "Royal Bounty",
        "author_kr": "프란체스 릿지 하벌갈",
        "author_en": "Frances Ridley Havergal",
        "year": 1879,
    },
    {
        "slug": "havergal-loyal-responses",
        "title": "충성스런 응답",
        "title_en": "Loyal Responses",
        "author_kr": "프란체스 릿지 하벌갈",
        "author_en": "Frances Ridley Havergal",
        "year": 1878,
    },
    {
        "slug": "havergal-ministry-song",
        "title": "노래의 사역",
        "title_en": "Ministry of Song",
        "author_kr": "프란체스 릿지 하벌갈",
        "author_en": "Frances Ridley Havergal",
        "year": 1869,
        "gutenberg_id": 22289,
    },
    {
        "slug": "guyon-method-prayer",
        "title": "짧은 기도 방법",
        "title_en": "A Short and Easy Method of Prayer",
        "author_kr": "귀용 부인",
        "author_en": "Madame Guyon",
        "year": 1685,
        "ccel_author": "guyon",
        "ccel_work": "prayer",
    },
    {
        "slug": "guyon-autobiography",
        "title": "귀용 부인 자서전",
        "title_en": "The Autobiography of Madame Guyon",
        "author_kr": "귀용 부인",
        "author_en": "Madame Guyon",
        "year": 1720,
        "gutenberg_id": 13090,
    },
    {
        "slug": "elizabeth-fry-journal",
        "title": "엘리자베스 프라이 일기",
        "title_en": "Memoir of the Life of Elizabeth Fry",
        "author_kr": "엘리자베스 프라이",
        "author_en": "Elizabeth Fry",
        "year": 1847,
    },
    {
        "slug": "anne-dutton-select",
        "title": "영적 서신 선집",
        "title_en": "Selected Spiritual Letters",
        "author_kr": "앤 더튼",
        "author_en": "Anne Dutton",
        "year": 1750,
    },
    # ── 카테고리 54: F.B. Meyer Core Works (10권) ──
    {
        "slug": "meyer-secret-guidance",
        "title": "인도하심의 비결",
        "title_en": "The Secret of Guidance",
        "author_kr": "F.B. 마이어",
        "author_en": "F. B. Meyer",
        "year": 1896,
    },
    {
        "slug": "meyer-abraham-obedience",
        "title": "아브라함: 믿음의 순종",
        "title_en": "Abraham The Obedience of Faith",
        "author_kr": "F.B. 마이어",
        "author_en": "F. B. Meyer",
        "year": 1897,
    },
    {
        "slug": "meyer-elijah-power",
        "title": "엘리야와 그의 능력의 비결",
        "title_en": "Elijah and the Secret of His Power",
        "author_kr": "F.B. 마이어",
        "author_en": "F. B. Meyer",
        "year": 1901,
    },
    {
        "slug": "meyer-paul-servant",
        "title": "바울: 예수 그리스도의 종",
        "title_en": "Paul A Servant of Jesus Christ",
        "author_kr": "F.B. 마이어",
        "author_en": "F. B. Meyer",
        "year": 1897,
    },
    {
        "slug": "meyer-moses-servant",
        "title": "하나님의 종 모세",
        "title_en": "Moses the Servant of God",
        "author_kr": "F.B. 마이어",
        "author_en": "F. B. Meyer",
        "year": 1893,
    },
    {
        "slug": "meyer-jeremiah-priest",
        "title": "예레미야: 제사장과 선지자",
        "title_en": "Jeremiah Priest and Prophet",
        "author_kr": "F.B. 마이어",
        "author_en": "F. B. Meyer",
        "year": 1894,
    },
    {
        "slug": "meyer-back-to-bethel",
        "title": "벧엘로 돌아가라",
        "title_en": "Back to Bethel",
        "author_kr": "F.B. 마이어",
        "author_en": "F. B. Meyer",
        "year": 1901,
    },
    {
        "slug": "meyer-christian-living",
        "title": "경건한 삶의 안내",
        "title_en": "The Directory of the Devout Life",
        "author_kr": "F.B. 마이어",
        "author_en": "F. B. Meyer",
        "year": 1904,
    },
    {
        "slug": "meyer-our-daily-homily-v1",
        "title": "매일의 강론 제1권",
        "title_en": "Our Daily Homily Vol 1",
        "author_kr": "F.B. 마이어",
        "author_en": "F. B. Meyer",
        "year": 1898,
    },
    {
        "slug": "meyer-our-daily-homily-v2",
        "title": "매일의 강론 제2권",
        "title_en": "Our Daily Homily Vol 2",
        "author_kr": "F.B. 마이어",
        "author_en": "F. B. Meyer",
        "year": 1898,
    },
    # ── 카테고리 55: George Whitefield & Revival Preachers (8권) ──
    {
        "slug": "whitefield-journals",
        "title": "조지 휫필드 일기",
        "title_en": "The Journals of George Whitefield",
        "author_kr": "조지 휫필드",
        "author_en": "George Whitefield",
        "year": 1756,
        "gutenberg_id": 11813,
    },
    {
        "slug": "whitefield-sermons-v1",
        "title": "조지 휫필드 설교 선집 제1권",
        "title_en": "Select Sermons of George Whitefield",
        "author_kr": "조지 휫필드",
        "author_en": "George Whitefield",
        "year": 1770,
        "ccel_author": "whitefield",
        "ccel_work": "sermons",
    },
    {
        "slug": "whitefield-sermons-v2",
        "title": "조지 휫필드 설교 선집 제2권",
        "title_en": "Selected Sermons of Whitefield",
        "author_kr": "조지 휫필드",
        "author_en": "George Whitefield",
        "year": 1770,
    },
    {
        "slug": "whitefield-letters-select",
        "title": "조지 휫필드 서신 선집",
        "title_en": "Select Letters of George Whitefield",
        "author_kr": "조지 휫필드",
        "author_en": "George Whitefield",
        "year": 1771,
    },
    {
        "slug": "whitefield-short-account",
        "title": "하나님의 섭리에 대한 짧은 기록",
        "title_en": "A Short Account of Gods Dealings with George Whitefield",
        "author_kr": "조지 휫필드",
        "author_en": "George Whitefield",
        "year": 1740,
    },
    {
        "slug": "nettleton-asahel-memoir",
        "title": "아사헬 네틀턴 회고록",
        "title_en": "Memoir of the Life and Character of Asahel Nettleton",
        "author_kr": "베넷 타일러",
        "author_en": "Bennet Tyler",
        "year": 1844,
    },
    {
        "slug": "mcheyne-sermons-select",
        "title": "로버트 머리 맥체인 설교 선집",
        "title_en": "Sermons of Robert Murray McCheyne",
        "author_kr": "로버트 머리 맥체인",
        "author_en": "Robert Murray McCheyne",
        "year": 1848,
        "ccel_author": "m/mcheyne",
        "ccel_work": "sermons",
    },
    {
        "slug": "bonar-diary-life",
        "title": "앤드류 보나르 일기와 생애",
        "title_en": "Andrew Bonar Diary and Life",
        "author_kr": "마조리 보나르",
        "author_en": "Marjory Bonar",
        "year": 1893,
    },
]

if __name__ == "__main__":
    process_all(BOOKS, delay=1.5)
