#!/usr/bin/env python3
"""Phase 6 배치 A: 카테고리 48-49 (선구적 개혁가, 네덜란드 개혁주의) — 22권."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from pipeline.scripts.phase5_utils import process_all

BOOKS = [
    # ── 카테고리 48: 선구적 개혁가 (8권) ──
    {
        "slug": "wycliffe-truth-scripture-sel",
        "title": "성경의 진리에 관하여 (선집)",
        "title_en": "On the Truth of Holy Scripture (selections)",
        "author_kr": "존 위클리프",
        "author_en": "John Wycliffe",
        "year": 1378,
    },
    {
        "slug": "wycliffe-pastoral-office",
        "title": "목회직에 관하여",
        "title_en": "On the Pastoral Office",
        "author_kr": "존 위클리프",
        "author_en": "John Wycliffe",
        "year": 1378,
    },
    {
        "slug": "wycliffe-english-works-sel",
        "title": "위클리프 영문 선집",
        "title_en": "English Works of Wycliffe (selections)",
        "author_kr": "존 위클리프",
        "author_en": "John Wycliffe",
        "year": 1380,
    },
    {
        "slug": "hus-de-ecclesia",
        "title": "교회론",
        "title_en": "On the Church (De Ecclesia)",
        "author_kr": "얀 후스",
        "author_en": "Jan Hus",
        "year": 1413,
    },
    {
        "slug": "hus-letters",
        "title": "후스 서신집",
        "title_en": "The Letters of John Hus",
        "author_kr": "얀 후스",
        "author_en": "Jan Hus",
        "year": 1415,
    },
    {
        "slug": "colet-romans-lectures",
        "title": "로마서 강의",
        "title_en": "Lectures on Romans (Enarratio)",
        "author_kr": "존 콜렛",
        "author_en": "John Colet",
        "year": 1497,
    },
    {
        "slug": "savonarola-sermons-sel",
        "title": "설교와 저술 선집",
        "title_en": "Selected Sermons and Writings",
        "author_kr": "지롤라모 사보나롤라",
        "author_en": "Girolamo Savonarola",
        "year": 1496,
    },
    {
        "slug": "wycliffe-on-simony",
        "title": "성직매매론",
        "title_en": "On Simony",
        "author_kr": "존 위클리프",
        "author_en": "John Wycliffe",
        "year": 1380,
    },
    # ── 카테고리 49: 네덜란드 개혁주의 황금기 (14권) ──
    {
        "slug": "brakel-reasonable-service-v1",
        "title": "성도의 합리적 예배 제1권: 신론·인간론",
        "title_en": "The Christian's Reasonable Service Vol.1",
        "author_kr": "빌헬무스 아 브라켈",
        "author_en": "Wilhelmus à Brakel",
        "year": 1700,
    },
    {
        "slug": "brakel-reasonable-service-v2",
        "title": "성도의 합리적 예배 제2권: 구원론",
        "title_en": "The Christian's Reasonable Service Vol.2",
        "author_kr": "빌헬무스 아 브라켈",
        "author_en": "Wilhelmus à Brakel",
        "year": 1700,
    },
    {
        "slug": "brakel-reasonable-service-v3",
        "title": "성도의 합리적 예배 제3권: 교회론·성례",
        "title_en": "The Christian's Reasonable Service Vol.3",
        "author_kr": "빌헬무스 아 브라켈",
        "author_en": "Wilhelmus à Brakel",
        "year": 1700,
    },
    {
        "slug": "brakel-reasonable-service-v4",
        "title": "성도의 합리적 예배 제4권: 종말론·신앙 실천",
        "title_en": "The Christian's Reasonable Service Vol.4",
        "author_kr": "빌헬무스 아 브라켈",
        "author_en": "Wilhelmus à Brakel",
        "year": 1700,
    },
    {
        "slug": "ames-marrow-theology",
        "title": "신학의 정수",
        "title_en": "The Marrow of Theology",
        "author_kr": "윌리엄 에임스",
        "author_en": "William Ames",
        "year": 1623,
    },
    {
        "slug": "ames-conscience-cases",
        "title": "양심론",
        "title_en": "Conscience with the Power and Cases Thereof",
        "author_kr": "윌리엄 에임스",
        "author_en": "William Ames",
        "year": 1630,
    },
    {
        "slug": "witsius-economy-covenants-v1",
        "title": "언약의 경륜 제1권",
        "title_en": "The Economy of the Covenants Vol.1",
        "author_kr": "헤르만 위치우스",
        "author_en": "Herman Witsius",
        "year": 1685,
    },
    {
        "slug": "witsius-economy-covenants-v2",
        "title": "언약의 경륜 제2권",
        "title_en": "The Economy of the Covenants Vol.2",
        "author_kr": "헤르만 위치우스",
        "author_en": "Herman Witsius",
        "year": 1685,
    },
    {
        "slug": "wollebius-compendium",
        "title": "기독교 신학 요강",
        "title_en": "Compendium of Christian Theology",
        "author_kr": "요하네스 볼레비우스",
        "author_en": "Johannes Wollebius",
        "year": 1626,
    },
    {
        "slug": "van-mastricht-prolegomena",
        "title": "이론-실천신학: 서론",
        "title_en": "Theoretical-Practical Theology: Prolegomena",
        "author_kr": "페트루스 반 마스트리흐트",
        "author_en": "Petrus van Mastricht",
        "year": 1682,
    },
    {
        "slug": "voetius-spiritual-life-sel",
        "title": "경건의 실천 (선집)",
        "title_en": "On the Practice of Godliness (selections)",
        "author_kr": "기스베르투스 부에티우스",
        "author_en": "Gijsbertus Voetius",
        "year": 1664,
    },
    {
        "slug": "teellinck-touchstone-true",
        "title": "참 기독교의 시금석",
        "title_en": "The Touchstone of True Christianity",
        "author_kr": "빌렘 텔린크",
        "author_en": "Willem Teellinck",
        "year": 1624,
    },
    {
        "slug": "lodensteyn-contemplations",
        "title": "묵상과 경건 저술 (선집)",
        "title_en": "Contemplations and Devotional Writings (sel.)",
        "author_kr": "요도쿠스 반 로덴스테인",
        "author_en": "Jodocus van Lodenstein",
        "year": 1676,
    },
    {
        "slug": "van-der-groe-earnest-call",
        "title": "간절한 부름",
        "title_en": "The Earnest Call",
        "author_kr": "테오도루스 반 데르 흐루",
        "author_en": "Theodorus van der Groe",
        "year": 1741,
    },
]

if __name__ == "__main__":
    process_all(BOOKS)
