#!/usr/bin/env python3
"""Phase 5 Batch E: 카테고리 59-61 (기도/금식, 원어도구, 어린이문학) — 28권."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from pipeline.scripts.phase5_utils import process_all

BOOKS = [
    # ── 카테고리 59: 기도와 금식의 전통 (10권) ──
    {
        "slug": "hallesby-prayer",
        "title": "기도",
        "title_en": "Prayer",
        "author_kr": "올레 할레스비",
        "author_en": "Ole Hallesby",
        "year": 1931,
    },
    {
        "slug": "forsyth-praying-man",
        "title": "기도의 영혼",
        "title_en": "The Soul of Prayer",
        "author_kr": "P.T. 포사이스",
        "author_en": "P. T. Forsyth",
        "year": 1916,
    },
    {
        "slug": "torrey-power-prayer",
        "title": "기도의 능력",
        "title_en": "The Power of Prayer",
        "author_kr": "R.A. 토레이",
        "author_en": "R. A. Torrey",
        "year": 1924,
        "ccel_author": "torrey",
        "ccel_work": "power",
    },
    {
        "slug": "torrey-prayer-revival",
        "title": "기도하는 방법",
        "title_en": "How to Pray",
        "author_kr": "R.A. 토레이",
        "author_en": "R. A. Torrey",
        "year": 1900,
        "ccel_author": "torrey",
        "ccel_work": "pray",
    },
    {
        "slug": "gordon-quiet-talks-prayer",
        "title": "기도에 대한 조용한 대화",
        "title_en": "Quiet Talks on Prayer",
        "author_kr": "S.D. 고든",
        "author_en": "S. D. Gordon",
        "year": 1904,
        "gutenberg_id": 13815,
    },
    {
        "slug": "prayer-classic-anthology",
        "title": "기도 보고 (모음집)",
        "title_en": "A Treasury of Prayer",
        "author_kr": "E.M. 바운즈 편",
        "author_en": "E. M. Bounds",
        "year": 1913,
    },
    {
        "slug": "steer-george-muller",
        "title": "하나님 안에서 기뻐하는 조지 뮬러",
        "title_en": "The Life of Trust",
        "author_kr": "조지 뮬러",
        "author_en": "George Muller",
        "year": 1885,
        "gutenberg_id": 2753,
        "note": "Roger Steer biography is modern; using George Muller's own 'The Life of Trust' (Gutenberg #2753) instead.",
    },
    {
        "slug": "whyte-bunyan-characters",
        "title": "번연 인물들 (선집)",
        "title_en": "Bunyan Characters",
        "author_kr": "알렉산더 화이트",
        "author_en": "Alexander Whyte",
        "year": 1893,
        "gutenberg_id": 6770,
    },
    {
        "slug": "mcintyre-hidden-life",
        "title": "기도의 숨겨진 삶",
        "title_en": "The Hidden Life of Prayer",
        "author_kr": "데이비드 매킨타이어",
        "author_en": "David McIntyre",
        "year": 1906,
    },
    {
        "slug": "bonhoeffer-cost-discipleship",
        "title": "제자도의 대가",
        "title_en": "The Cost of Discipleship",
        "author_kr": "디트리히 본회퍼",
        "author_en": "Dietrich Bonhoeffer",
        "year": 1937,
        "note": "English translation (1948) may not be public domain. Failure expected.",
    },

    # ── 카테고리 60: 히브리어/헬라어 원어 도구 (8권) ──
    {
        "slug": "thayers-greek-lexicon",
        "title": "세이어 신약 헬라어-영어 사전",
        "title_en": "Thayers Greek-English Lexicon of the New Testament",
        "author_kr": "조셉 세이어",
        "author_en": "Joseph Henry Thayer",
        "year": 1889,
    },
    {
        "slug": "vines-expository-dictionary",
        "title": "바인 신약 단어 해설 사전",
        "title_en": "Vines Expository Dictionary of New Testament Words",
        "author_kr": "W.E. 바인",
        "author_en": "W. E. Vine",
        "year": 1940,
    },
    {
        "slug": "wuest-word-studies-nt",
        "title": "바우에스트 헬라어 신약 단어 연구",
        "title_en": "Wuests Word Studies in the Greek New Testament",
        "author_kr": "케네스 바우에스트",
        "author_en": "Kenneth Wuest",
        "year": 1953,
    },
    {
        "slug": "strong-exhaustive-concordance",
        "title": "스트롱의 완전 일치",
        "title_en": "Strongs Exhaustive Concordance",
        "author_kr": "제임스 스트롱",
        "author_en": "James Strong",
        "year": 1890,
    },
    {
        "slug": "gesenius-hebrew-grammar-sel",
        "title": "게제니우스 히브리어 문법",
        "title_en": "Gesenius Hebrew Grammar",
        "author_kr": "W. 게제니우스",
        "author_en": "W. Gesenius",
        "year": 1910,
    },
    {
        "slug": "gesenius-hebrew-lexicon-sel",
        "title": "게제니우스 히브리어-칼대어 사전",
        "title_en": "Gesenius Hebrew-Chaldee Lexicon",
        "author_kr": "W. 게제니우스",
        "author_en": "W. Gesenius",
        "year": 1846,
    },
    {
        "slug": "robertson-word-pictures-nt",
        "title": "신약 성경의 단어 그림",
        "title_en": "Word Pictures in the New Testament",
        "author_kr": "A.T. 로버트슨",
        "author_en": "A. T. Robertson",
        "year": 1930,
    },
    {
        "slug": "young-analytical-concordance",
        "title": "영의 분석 일치",
        "title_en": "Youngs Analytical Concordance",
        "author_kr": "로버트 영",
        "author_en": "Robert Young",
        "year": 1879,
    },

    # ── 카테고리 61: 기독교 어린이 문학 (10권) ──
    {
        "slug": "stretton-jessica-first-prayer",
        "title": "제시카의 첫 기도",
        "title_en": "Jessicas First Prayer",
        "author_kr": "헤즈바 스트레튼",
        "author_en": "Hesba Stretton",
        "year": 1867,
        "gutenberg_id": 29006,
    },
    {
        "slug": "stretton-little-meg",
        "title": "꼬마 메그의 아이들",
        "title_en": "Little Megs Children",
        "author_kr": "헤즈바 스트레튼",
        "author_en": "Hesba Stretton",
        "year": 1868,
        "gutenberg_id": 18851,
    },
    {
        "slug": "stretton-pilgrim-street",
        "title": "순례자 거리",
        "title_en": "Pilgrim Street A Story of Manchester Life",
        "author_kr": "헤즈바 스트레튼",
        "author_en": "Hesba Stretton",
        "year": 1867,
        "gutenberg_id": 18906,
    },
    {
        "slug": "charlesworth-ministering-children",
        "title": "섬기는 어린이들",
        "title_en": "Ministering Children",
        "author_kr": "마리아 찰스워스",
        "author_en": "Maria Charlesworth",
        "year": 1854,
        "gutenberg_id": 20037,
    },
    {
        "slug": "charlesworth-england-home",
        "title": "영국의 자유농",
        "title_en": "Englands Yeomen",
        "author_kr": "마리아 찰스워스",
        "author_en": "Maria Charlesworth",
        "year": 1858,
    },
    {
        "slug": "sherwood-history-fairchild",
        "title": "페어차일드 가족 이야기",
        "title_en": "The History of the Fairchild Family",
        "author_kr": "메리 마사 셔우드",
        "author_en": "Mary Martha Sherwood",
        "year": 1818,
        "gutenberg_id": 13275,
    },
    {
        "slug": "yonge-little-duke",
        "title": "어린 공작",
        "title_en": "The Little Duke",
        "author_kr": "샬롯 영",
        "author_en": "Charlotte M. Yonge",
        "year": 1854,
        "gutenberg_id": 3820,
    },
    {
        "slug": "alcott-little-women",
        "title": "작은 아씨들",
        "title_en": "Little Women",
        "author_kr": "루이자 메이 올콧",
        "author_en": "Louisa May Alcott",
        "year": 1868,
        "gutenberg_id": 514,
    },
    {
        "slug": "macgregor-rob-roy",
        "title": "롭 로이 맥그레거",
        "title_en": "Rob Roy",
        "author_kr": "월터 스콧",
        "author_en": "Sir Walter Scott",
        "year": 1817,
        "gutenberg_id": 7025,
        "note": "Rob Roy is by Sir Walter Scott, not Mary Macgregor.",
    },
    {
        "slug": "farrar-eric-or-little",
        "title": "에릭 또는 조금씩",
        "title_en": "Eric or Little by Little",
        "author_kr": "프레드릭 패러",
        "author_en": "Frederic W. Farrar",
        "year": 1858,
        "gutenberg_id": 24150,
    },
]

if __name__ == "__main__":
    process_all(BOOKS, delay=1.5)
