#!/usr/bin/env python3
"""Phase 6 배치 C: 카테고리 52-53 (뉴잉글랜드 청교도, 빅토리아 성경학) — 25권."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from pipeline.scripts.phase5_utils import process_all

BOOKS = [
    # ── 카테고리 52: 뉴잉글랜드 청교도 (10권) ──
    {
        "slug": "shepard-ten-virgins-v1",
        "title": "열 처녀 비유 제1권",
        "title_en": "The Parable of the Ten Virgins Vol.1",
        "author_kr": "토마스 셰퍼드",
        "author_en": "Thomas Shepard",
        "year": 1660,
    },
    {
        "slug": "shepard-ten-virgins-v2",
        "title": "열 처녀 비유 제2권",
        "title_en": "The Parable of the Ten Virgins Vol.2",
        "author_kr": "토마스 셰퍼드",
        "author_en": "Thomas Shepard",
        "year": 1660,
    },
    {
        "slug": "shepard-sincere-convert",
        "title": "진실한 회심자",
        "title_en": "The Sincere Convert",
        "author_kr": "토마스 셰퍼드",
        "author_en": "Thomas Shepard",
        "year": 1641,
    },
    {
        "slug": "shepard-sound-believer",
        "title": "온전한 신자",
        "title_en": "The Sound Believer",
        "author_kr": "토마스 셰퍼드",
        "author_en": "Thomas Shepard",
        "year": 1645,
    },
    {
        "slug": "hooker-souls-preparation",
        "title": "영혼의 그리스도 영접 준비",
        "title_en": "The Soul's Preparation for Christ",
        "author_kr": "토마스 후커",
        "author_en": "Thomas Hooker",
        "year": 1632,
    },
    {
        "slug": "hooker-application-redemption",
        "title": "구속의 적용 (선집)",
        "title_en": "The Application of Redemption (sel.)",
        "author_kr": "토마스 후커",
        "author_en": "Thomas Hooker",
        "year": 1656,
    },
    {
        "slug": "cotton-mather-magnalia-sel",
        "title": "미국 기독교 위업 (선집)",
        "title_en": "Magnalia Christi Americana (selections)",
        "author_kr": "코튼 매더",
        "author_en": "Cotton Mather",
        "year": 1702,
    },
    {
        "slug": "cotton-mather-essays-good",
        "title": "선을 행하는 에세이",
        "title_en": "Essays to Do Good (Bonifacius)",
        "author_kr": "코튼 매더",
        "author_en": "Cotton Mather",
        "year": 1710,
        "gutenberg_id": 12936,
    },
    {
        "slug": "willard-child-of-light",
        "title": "어둠 속을 걷는 빛의 자녀",
        "title_en": "The Child of Light Walking in Darkness",
        "author_kr": "새뮤얼 윌러드",
        "author_en": "Samuel Willard",
        "year": 1659,
    },
    {
        "slug": "norton-orthodox-evangelist",
        "title": "정통 복음 전도자",
        "title_en": "The Orthodox Evangelist",
        "author_kr": "존 노턴",
        "author_en": "John Norton",
        "year": 1654,
    },
    # ── 카테고리 53: 빅토리아 성경학 황금기 (15권) ──
    {
        "slug": "lightfoot-galatians",
        "title": "갈라디아서 주석",
        "title_en": "Commentary on Galatians",
        "author_kr": "J.B. 라이트풋",
        "author_en": "J.B. Lightfoot",
        "year": 1865,
    },
    {
        "slug": "lightfoot-philippians",
        "title": "빌립보서 주석",
        "title_en": "Commentary on Philippians",
        "author_kr": "J.B. 라이트풋",
        "author_en": "J.B. Lightfoot",
        "year": 1868,
    },
    {
        "slug": "lightfoot-colossians-philemon",
        "title": "골로새서·빌레몬서 주석",
        "title_en": "Commentary on Colossians & Philemon",
        "author_kr": "J.B. 라이트풋",
        "author_en": "J.B. Lightfoot",
        "year": 1875,
    },
    {
        "slug": "lightfoot-apostolic-fathers-v1",
        "title": "사도교부 제1권: 클레멘트",
        "title_en": "The Apostolic Fathers Vol.1: Clement",
        "author_kr": "J.B. 라이트풋",
        "author_en": "J.B. Lightfoot",
        "year": 1869,
    },
    {
        "slug": "westcott-gospel-john",
        "title": "요한복음 주석",
        "title_en": "The Gospel According to St. John",
        "author_kr": "B.F. 웨스트콧",
        "author_en": "B.F. Westcott",
        "year": 1882,
    },
    {
        "slug": "westcott-epistle-hebrews",
        "title": "히브리서 주석",
        "title_en": "The Epistle to the Hebrews",
        "author_kr": "B.F. 웨스트콧",
        "author_en": "B.F. Westcott",
        "year": 1889,
    },
    {
        "slug": "westcott-epistles-john",
        "title": "요한서신 주석",
        "title_en": "The Epistles of St. John",
        "author_kr": "B.F. 웨스트콧",
        "author_en": "B.F. Westcott",
        "year": 1883,
    },
    {
        "slug": "godet-commentary-john-v1",
        "title": "요한복음 주석 제1권",
        "title_en": "Commentary on John Vol.1",
        "author_kr": "F.B. 고데",
        "author_en": "F.B. Godet",
        "year": 1877,
    },
    {
        "slug": "godet-commentary-john-v2",
        "title": "요한복음 주석 제2권",
        "title_en": "Commentary on John Vol.2",
        "author_kr": "F.B. 고데",
        "author_en": "F.B. Godet",
        "year": 1877,
    },
    {
        "slug": "godet-commentary-romans",
        "title": "로마서 주석",
        "title_en": "Commentary on Romans",
        "author_kr": "F.B. 고데",
        "author_en": "F.B. Godet",
        "year": 1879,
    },
    {
        "slug": "godet-commentary-1cor",
        "title": "고린도전서 주석",
        "title_en": "Commentary on 1 Corinthians",
        "author_kr": "F.B. 고데",
        "author_en": "F.B. Godet",
        "year": 1886,
    },
    {
        "slug": "godet-commentary-luke",
        "title": "누가복음 주석",
        "title_en": "Commentary on Luke",
        "author_kr": "F.B. 고데",
        "author_en": "F.B. Godet",
        "year": 1875,
    },
    {
        "slug": "griffith-thomas-principles",
        "title": "신학의 원리 (39개 조항 해설)",
        "title_en": "The Principles of Theology (39 Articles)",
        "author_kr": "W.H. 그리피스 토머스",
        "author_en": "W.H. Griffith Thomas",
        "year": 1930,
    },
    {
        "slug": "griffith-thomas-genesis",
        "title": "창세기부터 신명기까지",
        "title_en": "Through the Pentateuch Chapter by Chapter",
        "author_kr": "W.H. 그리피스 토머스",
        "author_en": "W.H. Griffith Thomas",
        "year": 1907,
    },
    {
        "slug": "bengel-gnomon-nt-sel",
        "title": "신약 주해 선집",
        "title_en": "Gnomon of the New Testament (selections)",
        "author_kr": "요한 알브레흐트 벵겔",
        "author_en": "Johann Albrecht Bengel",
        "year": 1742,
    },
]

if __name__ == "__main__":
    process_all(BOOKS)
